
[[_config_dsl]]
= Config DSL

Most plugins take their configuration from a centralized point: the Config DSL. This feature is added by the
`<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>` which is automatically applied by most plugins.

The DSL is comprised of the following elements

[source,groovy]
[subs="+macros"]
----
config {
    <<_org_kordamp_gradle_base,info>> { ... }
    <<_base_dependencyManagement,dependencyManagement>> { ... }
    <<_org_kordamp_gradle_bom,bom>> { ... }
    <<_org_kordamp_gradle_buildinfo,buildInfo>> { ... }
    <<_org_kordamp_gradle_licensing,licensing>> { ... }
    <<_org_kordamp_gradle_plugins,plugins>> { ... }
    <<_org_kordamp_gradle_publishing,publishing>> { ... }
    <<_org_kordamp_gradle_sourcestats,stats>> { ... }
    <<_org_kordamp_gradle_testing,testing>> { ... }
    artifacts {
        <<_org_kordamp_gradle_jar,jar>> { ... }
        <<_org_kordamp_gradle_minpom,minpom>> { ... }
        <<_org_kordamp_gradle_source,source>> { ... }
    }
    docs {
        <<_org_kordamp_gradle_guide,guide>> { ... }
        <<_org_kordamp_gradle_groovydoc,groovydoc>> { ... }
        <<_org_kordamp_gradle_javadoc,javadoc>> { ... }
        <<_org_kordamp_gradle_sourcehtml,sourceHtml>> { ... }
        <<_org_kordamp_gradle_sourcexref,sourceXref>> { ... }
    }
    coverage {
        <<_org_kordamp_gradle_coveralls,coveralls>> { ... }
        <<_org_kordamp_gradle_jacoco,jacoco>> { ... }
    }
    quality {
        <<_org_kordamp_gradle_checkstyle,checkstyle>> { ... }
        <<_org_kordamp_gradle_codenarc,codenarc>> { ... }
        <<_org_kordamp_gradle_cpd,cpd>> { ... }
        <<_org_kordamp_gradle_errorprone,errorprone>> { ... }
        <<_org_kordamp_gradle_pmd,pmd>> { ... }
        <<_org_kordamp_gradle_spotbugs,spotbugs>> { ... }
        <<_org_kordamp_gradle_sonar,sonar>> { ... }
    }
}
----

Each one of these elements (except for `info`) expose a property named `enabled` that can be used to turn on or
off all of the behavior provided by the associated plugin. This property is set to `true` by default.

Most of the time it's enough to configure the DSL on the root project, as settings are automatically applied to all subprojects.
However it's also possible to override a particular root setting should the need arises, just define a `config` block
on the subproject's build file and override the settings you need. Here's for example how a child project may skip
publications completely:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.build.gradle (root)
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    info { ... }
    // additional configuration
}

allprojects {
    repositories {
        mavenCentral()
    }
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.build.gradle.kts (root)
----
plugins {
    id("org.kordamp.gradle.project") version "{project-version}"
}

config {
    info { ... }
    // additional configuration
}

allprojects {
    repositories {
        mavenCentral()
    }
}
----

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.build.gradle (child)
----
config {
    publishing { enabled = false }
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.build.gradle.kts (child)
----
config {
    publishing { enabled = false }
}
----

