= jdeps-gradle-plugin
:linkattrs:
:project-name: kordamp-gradle-plugins
:plugin-version: 0.1.0-SNAPSHOT

image:http://img.shields.io/travis/aalmiray/{project-name}/master.svg["Build Status", link="https://travis-ci.org/aalmiray/{project-name}"]
image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]
image:https://api.bintray.com/packages/aalmiray/kordamp/{project-name}/images/download.svg[link="https://bintray.com/aalmiray/kordamp/{project-name}/_latestVersion"]
image:https://img.shields.io/badge/donations-Patreon-orange.svg[link="https://www.patreon.com/user?u=6609318"]

---

A set of opinionated Gradle plugins that provide common behavior observed in Maven, and more!

== Usage

Option #1
[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.kordamp.gradle:{plugin-id}:{plugin-version}'
    }
}
apply plugin: 'org.kordamp.jdeps'
----

Option #2
[source,groovy]
[subs="attributes"]
----
plugins {
    id '{plugin-id}' version '{plugin-version}'
}
----

Where `{plugin-id}` stands for any of the ids described in the following section

== Plugins

=== Base

id: `org.kordamp.gradle.base`

Responsibilities:

 * Creates an extension named `projectConfiguration` that serves as the central point of configuration for all
other plugins. This extension has the following properties

[header, cols="4*"]
|===
| Name    | Type    | Default Value | Description
| sources | boolean | true          | Generates `sourceJar` is active
| apidocs | boolean | true          | Generates `javadoc`and `javadocJar` if active
| minpom  | boolean | true          | Generates `minPom` if active
| release | boolean | false         | Customizes Jar manifest and metainf if active
|===

=== BuildInfo

id: `org.kordamp.gradle.build-info`

Responsibilities:

 * Defines a set of build related properties and attaches them to the `rootProject`. These properties are

[header, cols="3*"]
|===
| Name             | Type             | Description
| buildTimeAndDate | `java.util.Date` | A `java.util.Date` instance representing the current time
| buildDate        | String           | The value of `buildTimeAndDate` formatted with "yyyy-MM-dd"
| buildtime        | String           | The value of `buildTimeAndDate` formatted with "HH:mm:ss.SSSZ"
| buildBy          | String           | The value of the `user.name` System property
| buildRevision    | String           | The value of the latest commit hash
| buildJdk         | String           | Concatenation of the following System properties [`java.version`, `java.vendor`, `java.vm.version]
| buildCreatedBy   | String           | The Gradle version used in the build
|===

NOTE: This plugin implicitly applies `net.nemerosa:versioning` to obtain SCM information.

=== SourceJar

id: `org.kordamp.gradle.source-jar`

Responsibilities:

 * Creates a `Jar` task that packages sources per `SourceSet`.
 * Configures a `MavenPublication` that matches the sourceSet's name.
 * Attaches the source JAR artifact to the custom `MavenPublication`.
 * Creates a composite `allSourceJars` tasks that triggers every other `sourceJar` in the current project.

=== Apidocs

id: `org.kordamp.gradle.apidoc`

Responsibilities:

 * Creates a `Javadoc` task per `SourceSet`.
 * Creates a `Jar` task that packages javadoc per `SourceSet`.
 * Configures a `MavenPublication` that matches the sourceSet's name.
 * Attaches the javadoc JAR artifact to the custom `MavenPublication`.
 * Creates a composite `allJavadocJars` tasks that triggers every other `javadocJar` in the current project.

=== MinPom

id: `org.kordamp.gradle.minpom`

Responsibilities:

 * Creates a minimum `pom.xml` file per `SourceSet`.
 * Creates a minimum `pom.properties` file per `SourceSet`.

=== Jar

id: `org.kordamp.gradle.jar`

Responsibilities:

 * Creates a `Jar` task per `SourceSet`.
 * If the `release` property is enabled, configures manifest entries provided by `BuildInfo`.
 * If the `release` property is enabled, adds the output of the matching `minpom` task to `metaInf`.

=== Project

id: `org.kordamp.gradle.project`

Responsibilities:

 * Applies all previous projects

