
[[_org_kordamp_gradle_base]]
= Base

[horizontal]
id:: `org.kordamp.gradle.base`
class:: `org.kordamp.gradle.plugin.base.BasePlugin`
    (link:api/org/kordamp/gradle/plugin/base/BasePlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/base/BasePlugin.html[source])

Enables de configuration DSL. Settings made via this DSL are consumed by multiple plugins.

[[_org_kordamp_gradle_base_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    release
    <<_base_info,info>> {
        name
        description
        inceptionYear
        vendor
        tags

        <<_base_info_links,links>> {
            website
            issueTracker
            scm
        }

        <<_base_info_scm,scm>> {
            url
            tag
            connection
            developerConnection
        }

        <<_base_info_organization,organization>> {
            name
            url
        }

        <<_base_info_specification,specification>> {
            enabled
            title
            version
            vendor
        }

        <<_base_info_implementation,implementation>> {
            enabled
            title
            version
            vendor
        }

        <<_base_info_credentials,credentials>> {
            github {
                username
                password
            }
            sonatype {
                username
                password
            }
            named {
                name
                username
                password
            }
        }

        <<_base_info_repositories,repositories>> {
            <<_base_info_repository,repository>> {
                name
                url
                credentials {
                    username
                    passsword
                }
            }
        }

        <<_base_info_people,people>> {
            <<_base_info_person,person>> {
                id
                name
                email
                url
                roles
                timezone
                <<_base_info_organization,organization>> {
                    name
                    url
                }
                properties
            }
        }

        <<_base_info_issueManagement,issueManagement>> {
            system
            url
        }

        <<_base_info_ciManagement,ciManagement>> {
            system
            url
        }

        <<_base_info_mailingLists,mailingLists>> {
            <<_base_info_mailingList,mailingList>> {
                name
                subscribe
                unsubscribe
                post
                archive
                otherArchives
            }
        }
    }
}
----

The `release` flag should be set to `true` (default is `false`) when a release (any kind of release, even snapshot) is
needed. At the moment this flag controls enrichment of JAR manifests as explained in the <<_org_kordamp_gradle_jar,Jar>>
plugin. Other plugins may hook into this flag to provide additional configuration and behavior.

[[_base_info]]
*general*

[options="header", cols="5*"]
|===
| Name          | Type         | Required | Default Value | Description
| name          | String       | no       | project.name  | Mapped to the `<name>` block in POM
| description   | String       | yes      |               | Mapped to the `<description>` block in POM
| inceptionYear | String       | no       | current year  | Mapped to the `<inceptionYear>` block in POM
| vendor        | String       | no*      |               |
| tags          | List<String> | no       | []            |
|===

The value for `vendor` may be omitted if a value for `organization.name` is given.

[[_base_info_links]]
*links*

[options="header", cols="5*"]
|===
| Name         | Type   | Required | Default Value | Description
| website      | String | yes      | empty         | Mapped to the `<url>` block in POM.
                                                      Mapped to `bintray.pkg.websiteUrl`
| issueTracker | String | no*      | empty         | Mapped to `bintray.pkg.issueTracker`
| scm          | String | no*      | empty         | Mapped to the `<scm>` block in POM.
                                                     Mapped to `bintray.pkg.websiteUrl`
|===

Values for `issueTracker` and `scm` should be defined if the `<<_org_kordamp_gradle_bintray,org.kordamp.gradle.bintray>>`
plugin is used.

[[_base_info_scm]]
*scm*

[options="header", cols="5*"]
|===
| Name                | Type   | Required | Default Value | Description
| url                 | String | yes      | empty         | Mapped to the `<scm><url>` block in POM.OM.
| connection          | String | no*      | empty         | Mapped to the `<scm><connection>` block in POM.`
| developerconnection | String | no*      | empty         | Mapped to the `<scm><developerConnection>` block in POM.
|===

This block has precedence over `links.scm`.

[[_base_info_organization]]
*organization*

[options="header", cols="5*"]
|===
| Name | Type   | Required | Default Value | Description
| name | String | no       |               | The name of the organization
| url  | String | no       |               | The URL of the organization (website perhaps).
|===

This block is optional.

[[_base_info_specification]]
*specification*

[options="header", cols="5*"]
|===
| Name    | Type    | Required | Default Value   | Description
| enabled | boolean | no       | true            | JAR manifest entries will be updated if `true`
| title   | String  | no       | project.name    | Mapped to `Specification-Title` manifest entry
| version | String  | no       | project.version | Mapped to `Specification-Version` manifest entry
| vendor  | String  | no       | info.vendor     | Mapped to `Specification-Vendor` manifest entry
|===

This block is optional.

[[_base_info_implementation]]
*implementation*

[options="header", cols="5*"]
|===
| Name    | Type    | Required | Default Value   | Description
| enabled | boolean | no       | true            | JAR manifest entries will be updated if `true`
| title   | String  | no       | project.name    | Mapped to `Implementation-Title` manifest entry
| version | String  | no       | project.version | Mapped to `Implementation-Version` manifest entry
| vendor  | String  | no       | info.vendor     | Mapped to `Implementation-Vendor` manifest entry
|===

This block is optional.

[[_base_info_credentials]]
*credentials*

[options="header", cols="5*"]
|===
| Name     | Type        | Required | Default Value   | Description
| github   | Credentials | no*      |                 | Username/Password for connecting to GitHub
| sonatype | Credentials | no*      |                 | Username/Password for connecting to Maven Central
| named    | Credentials | no*      |                 | Defines a named credentials entry. Name may match a repository entry.
|===

The `sonatype` entry may be used by the `<<_org_kordamp_gradle_bintray,org.kordamp.gradle.bintray>>` plugin to configure
auto-sync with Maven Central when pushing a publication. Named credentials my match the name of a repository, in which
case they will be used during artifact publication on the matching repository.

This block is optional.

[[_base_info_repositories]]
*repositories*

This block defines data associated with a particular repository. Entries may be used during publication.

[[_base_info_repository]]
*repository*

[options="header", cols="5*"]
|===
| Name        | Type        | Required | Default Value | Description
| name        | String      | no*      |               | The name of the repository
| url         | String      | no*      |               | The URL of the repository
| credentials | Credentials | no*      |               | Values mapped to `credentials` block
|===

The `credentials` entry is optional. Credentials may be defined locally to the repository or globally using the
<<_base_info_credentials,credentials>> block. Local credentials have precedence over global credentials that match
the repository name.

[[_base_info_people]]
*people*

This block defines data associated with a particular person.

This block is optional if none of the following plugins are used: `<<_org_kordamp_gradle_javadoc,org.kordamp.gradle.javadoc>>`,
`<<_org_kordamp_gradle_groovydoc,org.kordamp.gradle.groovydoc>>`, `<<_org_kordamp_gradle_apidoc,org.kordamp.gradle.apidoc>>`,
`<<_org_kordamp_gradle_publishing,org.kordamp.gradle.publishing>>`, `<<_org_kordamp_gradle_bintray,org.kordamp.gradle.bintray>>`.

[[_base_info_person]]
*person*

[options="header", cols="5*"]
|===
| Name         | Type                | Required | Default Value | Description
| id           | String              | no*      |               | Mapped to the `<id>` block in POM
| name         | String              | no*      |               | Mapped to the `<name>` block in POM
| email        | String              | no       |               | Mapped to the `<email>` block in POM
| url          | String              | no       |               | Mapped to the `<url>` block in POM
| organization | Organization        | no       |               | Mapped to the `<organizationName>` and `<organizationUrl>` blocks in POM
| roles        | List<String>        | no       |               | Mapped to the `<roles>` block in POM
| timezone     | String              | no       |               | Mapped to the `<timezone>` block in POM
| properties   | Map<String, Object> | no       | [:]           | Mapped to the `<properties>` block in POM
|===

At least `id` or `name` must be defined. If a `developer` role exists then the person instance is mapped to a `<developer>`
block in the POM. If a `contributor` role exists then the person instance is maped to a `<contributor>` block in the POM.

[[_base_info_issueManagement]]
*issueManagement*

[options="header", cols="5*"]
|===
| Name        | Type        | Required | Default Value | Description
| system      | String      | no       |               | The system value of the `<issueManagement>` block in POM
| url         | String      | no       |               | The url value of the `<issueManagement>` block in POM
|===

[[_base_info_ciManagement]]
*ciManagement*

[options="header", cols="5*"]
|===
| Name        | Type        | Required | Default Value | Description
| system      | String      | no       |               | The system value of the `<ciManagement>` block in POM
| url         | String      | no       |               | The url value of the `<ciManagement>` block in POM
|===

[[_base_info_mailingLists]]
*mailingLists*

This block defines a list of MailingList entries.

[[_base_info_mailingList]]
*mailingList*

[options="header", cols="5*"]
|===
| Name          | Type         | Required | Default Value | Description
| name          | String       | no*      |               | Mapped to the `<name>` block in POM
| subscribe     | String       | no       |               | Mapped to the `<subscribe>` block in POM
| unsubscribe   | String       | no       |               | Mapped to the `<unsubscribe>` block in POM
| post          | String       | no       |               | Mapped to the `<post>` block in POM
| archive       | String       | no       |               | Mapped to the `<archive>` block in POM
| otherArchives | List<String> | no       |               | Mapped to the `<otherArchives>` block in POM
|===

At least `name` must be defined.

[[_org_kordamp_gradle_base_sysprops]]
=== System Properties

org.kordamp.gradle.base.validate:: Perform validation on DSL settings. Defaults to `true`.

[[_org_kordamp_gradle_base_tasks]]
== Tasks

[[_task_effective_settings]]
=== EffectiveSettings

Displays resolved settings

[horizontal]
Name:: effectiveSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.EffectiveSettingsTask`

.Options
[horizontal]
section:: The section to generate the report for.
sections:: The sections to generate the report for.
show-secrets:: Show secret values instead of masked values. Value masking is applied to properties that contain any
of the following words: `secret`, `password`, `credential`, `token`, `apikey`. The list of words can be overriden by
setting a System property named `kordamp.secret.keywords` to a comma delimited String, such as `password,secret`.

You may specify either of the two, be advised that `sections` has precedence over `section`. All sections will be displayed
if neither of these options is specified. Section names match entries found in the <<_project_dsl,DSL>>.

[[_task_extensions]]
=== Extensions

Displays all extensions applied to a project

[horizontal]
Name:: effectiveSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.ExtensionsTask`

==== Example Output

For a project defined as follows

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

Invoking these command

[source]
----
$ ./gradlew :extensions
----

Results in the following output

[source]
----
> Task :extensions
extension 0:
    name: ext
    type: org.gradle.api.plugins.ExtraPropertiesExtension

extension 1:
    name: defaultArtifacts
    type: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet

extension 2:
    name: config
    type: org.kordamp.gradle.plugin.base.ProjectConfigurationExtension

extension 3:
    name: reporting
    type: org.gradle.api.reporting.ReportingExtension

extension 4:
    name: jacoco
    type: org.gradle.testing.jacoco.plugins.JacocoPluginExtension

extension 5:
    name: downloadLicenses
    type: nl.javadude.gradle.plugins.license.DownloadLicensesExtension

extension 6:
    name: license
    type: nl.javadude.gradle.plugins.license.LicenseExtension

extension 7:
    name: signing
    type: org.gradle.plugins.signing.SigningExtension

extension 8:
    name: effectiveConfig
    type: org.kordamp.gradle.plugin.base.ProjectConfigurationExtension

extension 9:
    name: versioning
    type: net.nemerosa.versioning.VersioningExtension
----

[[_task_groovy_compiler_settings]]
=== GroovyCompilerSettings

Display compiler configuration

[horizontal]
Name:: groovyCompilerSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.GroovyCompilerSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
task:: The task to generate the report for.
tasks:: The tasks to generate the report for.

You may specify either of the two, be advised that `tasks` has precedence over `task`. All tasks will be displayed
if neither of these options is specified.

[[_task_java_compiler_settings]]
=== JavaCompilerSettings

Display compiler configuration

[horizontal]
Name:: javaCompilerSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.JavaCompilerSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
task:: The task to generate the report for.
tasks:: The tasks to generate the report for.

You may specify either of the two, be advised that `tasks` has precedence over `task`. All tasks will be displayed
if neither of these options is specified.

[[_task_list_included_builds]]
=== ListIncludedBuilds

Lists all included builds in this project

[horizontal]
Name:: listIncludedBuilds
Type:: `org.kordamp.gradle.plugin.base.tasks.ListIncludedBuildsTask`

==== Example Output

For a project defined as follows

[source,groovy]
----
.
├── build.gradle
└── settings.gradle
----

[source,groovy,subs="verbatim,attributes"]
.settings.gradle
----
includeBuild '../build1'
includeBuild '../build2'
----

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

Invoking these command

[source]
----
$ ./gradlew :listIncludedBuilds
----

Results in the following output

[source]
----
> Task :listIncludedBuilds
Total included builds: 2

build1:
    projectDir: /tmp/build1

build12:
    projectDir: /tmp/build2
----

[[_task_list_projects]]
=== ListProjects

Lists all projects

[horizontal]
Name:: listProjects
Type:: `org.kordamp.gradle.plugin.base.tasks.ListProjectsTask`

.Options
[horizontal]
absolute:: Should paths be printed as absolutes or not. Defaults to `false`.

==== Example Output

For a project defined as follows

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
└── subprojects
    ├── project1
    │   ├── project1.gradle
    └── project2
        └── project2.gradle
----

[source,groovy,subs="verbatim,attributes"]
.settings.gradle
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.kordamp.gradle:settings-gradle-plugin:{project-version}'
    }
}
apply plugin: 'org.kordamp.gradle.settings'
----

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

[source,groovy,subs="verbatim,attributes"]
.subprojects/project1.gradle
----
apply plugin: 'java'
----

[source,groovy,subs="verbatim,attributes"]
.subprojects/project2.gradle
----
apply plugin: 'java'
----

Invoking these command

[source]
----
$ ./gradlew :listProjects
----

Results in the following output

[source]
----
> Task :listProjects
Total projects: 3

sample:
    root: true
    path: :
    projectDir: /tmp/sample
    buildFile: /tmp/sample/build.gradle
    buildDir: /tmp/sample/build
 
project1:
    path: :project1
    projectDir: subprojects/project1
    buildFile: subprojects/project1/project1.gradle
    buildDir: subprojects/project1/build
 
project2:
    path: :project2
    projectDir: subprojects/project2
    buildFile: subprojects/project2/project2.gradle
    buildDir: subprojects/project2/build
----

[[_task_plugins]]
=== Plugins

Displays all plugins applied to a project

[horizontal]
Name:: plugins
Type:: `org.kordamp.gradle.plugin.base.tasks.PluginsTask`

==== Example Output

For a project defined as follows

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

Invoking these command

[source]
----
$ ./gradlew :plugins
----

Results in the following output

[source]
----
> Task :plugins
plugin 0:
    id: build-init
    implementationClass: org.gradle.buildinit.plugins.BuildInitPlugin

plugin 1:
    id: wrapper
    implementationClass: org.gradle.buildinit.plugins.WrapperPlugin

plugin 2:
    id: help-tasks
    implementationClass: org.gradle.api.plugins.HelpTasksPlugin

plugin 3:
    id: lifecycle-base
    implementationClass: org.gradle.language.base.plugins.LifecycleBasePlugin

plugin 4:
    id: base
    implementationClass: org.gradle.api.plugins.BasePlugin

plugin 5:
    id: org.kordamp.gradle.base
    implementationClass: org.kordamp.gradle.plugin.base.BasePlugin
    enabled: true

plugin 6:
    id: reporting-base
    implementationClass: org.gradle.api.plugins.ReportingBasePlugin

plugin 7:
    id: jacoco
    implementationClass: org.gradle.testing.jacoco.plugins.JacocoPlugin

plugin 8:
    id: org.kordamp.gradle.jacoco
    implementationClass: org.kordamp.gradle.plugin.jacoco.JacocoPlugin
    enabled: true

plugin 9:
    id: com.github.hierynomus.license-report
    implementationClass: com.hierynomus.gradle.license.LicenseReportingPlugin

plugin 10:
    id: com.github.hierynomus.license-base
    implementationClass: com.hierynomus.gradle.license.LicenseBasePlugin

plugin 11:
    id: license
    implementationClass: nl.javadude.gradle.plugins.license.LicensePlugin

plugin 12:
    id: org.kordamp.gradle.licensing
    implementationClass: org.kordamp.gradle.plugin.licensing.LicensingPlugin
    enabled: false

plugin 13:
    id: org.kordamp.gradle.build-info
    implementationClass: org.kordamp.gradle.plugin.buildinfo.BuildInfoPlugin
    enabled: true

plugin 14:
    id: org.kordamp.gradle.source-jar
    implementationClass: org.kordamp.gradle.plugin.source.SourceJarPlugin
    enabled: true

plugin 15:
    id: org.kordamp.gradle.javadoc
    implementationClass: org.kordamp.gradle.plugin.javadoc.JavadocPlugin
    enabled: true

plugin 16:
    id: org.kordamp.gradle.groovydoc
    implementationClass: org.kordamp.gradle.plugin.groovydoc.GroovydocPlugin
    enabled: false

plugin 17:
    id: org.kordamp.gradle.apidoc
    implementationClass: org.kordamp.gradle.plugin.apidoc.ApidocPlugin
    enabled: true

plugin 18:
    id: org.kordamp.gradle.minpom
    implementationClass: org.kordamp.gradle.plugin.minpom.MinPomPlugin
    enabled: true

plugin 19:
    id: org.kordamp.gradle.jar
    implementationClass: org.kordamp.gradle.plugin.jar.JarPlugin
    enabled: true

plugin 20:
    id: org.kordamp.gradle.publishing
    implementationClass: org.kordamp.gradle.plugin.publishing.PublishingPlugin
    enabled: true

plugin 21:
    id: signing
    implementationClass: org.gradle.plugins.signing.SigningPlugin

plugin 22:
    id: org.kordamp.gradle.source-stats
    implementationClass: org.kordamp.gradle.plugin.stats.SourceStatsPlugin
    enabled: true

plugin 23:
    id: org.kordamp.gradle.source-html
    implementationClass: org.kordamp.gradle.plugin.sourcehtml.SourceHtmlPlugin
    enabled: true

plugin 24:
    id: org.kordamp.gradle.bintray
    implementationClass: org.kordamp.gradle.plugin.bintray.BintrayPlugin
    enabled: true

plugin 25:
    id: org.kordamp.gradle.testing
    implementationClass: org.kordamp.gradle.plugin.testing.TestingPlugin
    enabled: true

plugin 26:
    id: com.github.ben-manes.versions
    implementationClass: com.github.benmanes.gradle.versions.VersionsPlugin

plugin 27:
    id: org.kordamp.gradle.project
    implementationClass: org.kordamp.gradle.plugin.project.ProjectPlugin

plugin 28:
    id: net.nemerosa.versioning
    implementationClass: net.nemerosa.versioning.VersioningPlugin
----

[[_task_properties]]
=== ProjectProperties

Displays all properties found in a project

[horizontal]
Name:: projectProperties
Type:: `org.kordamp.gradle.plugin.base.tasks.PropertiesTask`

.Options
[horizontal]
section:: The section to generate the report for.
show-secrets:: Show secret values instead of masked values. Value masking is applied to properties that contain any
of the following words: `secret`, `password`, `credential`, `token`, `apikey`. The list of words can be overriden by
setting a System property named `kordamp.secret.keywords` to a comma delimited String, such as `password,secret`.

Valid values for `section` are: project, ext.

==== Example Output

For a project defined as follows

[source,java]
.~/.gradle/gradle.properties
----
global_property = global
----

[source,java]
.gradle.properties
----
version        = 0.0.0
group          = org.kordamp.sample.acme
local_property = local
----

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

ext.build_property = 'build'

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

Invoking these command

[source]
----
$ ./gradlew :projectProperties -Pproject_property=project
----

Results in the following output

[source]
----
> Task :projectProperties
project:
    name: sample
    version: 0.0.0
    group: org.kordamp.sample.acme
    path: :
    displayName: root project 'sample'
    projectDir: /tmp/sample
    buildFile: /tmp/sample/build.gradle
    buildDir: /tmp/sample/build

ext:
    build_property: build
    global_property: global
    local_property: local
    project_property: project
----

[[_task_repositories]]
=== Repositories

Displays all repositories used for resolving project dependencies

[horizontal]
Name:: repositories
Type:: `org.kordamp.gradle.plugin.base.tasks.RepositoriesTask`

==== Example Output

For a project defined as follows

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}

repositories {
    jcenter()
    mavenCentral()
    flatDir { dirs 'lib' }
}
----

Invoking these command

[source]
----
$ ./gradlew :repositories
----

Results in the following output

[source]
----
> Task :repositories
repository 0:
    type: maven
    name: BintrayJCenter
    url: https://jcenter.bintray.com/

repository 1:
    type: maven
    name: MavenRepo
    url: https://repo.maven.apache.org/maven2/

repository 2:
    type: flatDir
    name: flatDir
    dirs:
        /tmp/sample/lib
----

[[_task_test_settings]]
=== TestSettings

Display test task configuration

[horizontal]
Name:: testSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.TestSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
task:: The task to generate the report for.
tasks:: The tasks to generate the report for.

You may specify either of the two, be advised that `tasks` has precedence over `task`. All tasks will be displayed
if neither of these options is specified.
