
[[_org_kordamp_gradle_functionaltest]]
= FunctionalTest

[horizontal]
id:: `org.kordamp.gradle.functional-test`
class:: `org.kordamp.gradle.plugin.functionaltest.FunctionalTestPlugin`
    (link:api/org/kordamp/gradle/plugin/functionaltest/FunctionalTestPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/functionaltest/FunctionalTestPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`

Responsibilities:

 * Create two additional configurations: `functionalTestImplementation` and `functionalTestRuntimeOnly`. These configurations
   extend from `imlementation` and `runtimeOnly` respectively.
 * Create a `SourceSet` named `functionalTest` pointing to `src/main/[java|groovy]`.
 * Create a `Test` task named `functionalTest` pointing to `src/functional-test/[java|groovy]`.
 * Create a `TestReport` task named `functionalTestReport`. This task is added as a dependency to `check`.

NOTE: You must add testing dependencies to `functionalTestImplementation` as this configuration is independent from `testImplementation`.

