
[[_org_kordamp_gradle_javadoc]]
= Javadoc

[horizontal]
id:: `org.kordamp.gradle.javadoc`
class:: `org.kordamp.gradle.plugin.javadoc.JavadocPlugin`
    (link:api/org/kordamp/gradle/plugin/javadoc/JavadocPlugin.html[javadoc],
     link:api-html/org/kordamp/gradle/plugin/javadoc/JavadocPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`

Generates and packages Javadoc documentation.

[[_org_kordamp_gradle_javadoc_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    javadoc {
        enabled
        includes
        excludes
        title
        options { ... }
        <<_javadoc_autolinks,autoLinks>> {
            enabled
            configurations
            excludes
            linksOffline
        }
    }
}
----

[options="header", cols="5*"]
|===
| Name     | Type                  | Required | Default Value | Description
| enabled  | boolean               | no       | true          | Disables `org.kordamp.gradle.javadoc` plugin if `false`
| includes | Set<String>           | no       | []            |
| excludes | Set<String>           | no       | []            |
| title    | String                | no       |               |
| options  | MinimalJavadocOptions | no       |               | Supports all options from `link:https://docs.gradle.org/4.10/javadoc/org/gradle/external/javadoc/StandardJavadocDocletOptions.html[StandardJavadocDocletOptions]`.
|===

.Methods

void exclude(String):: Adds a source exclusion rule (Ant pattern).
void include(String):: Adds a source inclusion rule (Ant pattern).

This block is optional.

[[_javadoc_autolinks]]
*autoLinks*

[options="header", cols="5*"]
|===
| Name           | Type         | Required | Default Value                                                | Description
| enabled        | boolean      | no       | true                                                         | Disables generation of auto links if `false`
| configurations | List<String> | no       | ['compile', 'compileOnly', 'annotationProcessor', 'runtime'] | Configurations to be checked for dependencies
| excludes       | Set<String>  | no       | []                                                           | Dependencies to be excluded. Format: '${artifactId}-${version}'
|===

.Methods

void exclude(String):: Adds a link exclusion rule (Regex pattern).
void offlineLink(String, String):: Adds an offline link definition. The first argument is for the string to be embedded in the
`<a href>` links, and the second tells the javadoc tool where to find either the `package-list` or `element-list` file.

Offline links are automatically calculated for project dependencies using absolute paths. These paths are skipped when the
`<<_org_kordamp_gradle_base_dsl,release>>` flag is set to `true`.

[[_org_kordamp_gradle_javadoc_tasks]]
== Tasks

[[_task_check_auto_links]]
=== CheckAutoLinks

Checks if generated Javadoc auto links are reachable.

[horizontal]
Name:: checkAutoLinks
Type:: `org.kordamp.gradle.plugin.javadoc.CheckAutoLinksTask`

[[_task_javadoc]]
=== Javadoc

Generates Javadoc API documentation. +
Consumes settings from `config.<<_org_kordamp_gradle_javadoc_dsl,javadoc>>`.

[horizontal]
Name:: javadoc
Type:: `org.gradle.api.tasks.javadoc.Javadoc`

.Properties
[horizontal]
destinationDir:: `${project.buildDir}/docs/javadoc`

[[_task_javadoc_jar]]
=== JavadocJar

An archive of the Javadoc API docs.

[horizontal]
Name:: javadocJar
Type:: `org.gradle.api.tasks.bundling.Jar`

.Properties
[horizontal]
classifier:: javadoc
destinationDir:: `${project.buildDir}/build/libs`
from:: `javadoc.destinationDir`

