
[[_org_kordamp_gradle_kotlin_project]]
= KotlinProject

[horizontal]
id:: `org.kordamp.gradle.kotlin-project`
class:: `org.kordamp.gradle.plugin.project.kotlin.KotlinProjectPlugin`
    (link:api/org/kordamp/gradle/plugin/project/kotlin/KotlinProjectPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/project/kotlin/KotlinProjectPlugin.html[source])
applies:: `<<_org_kordamp_gradle_java_project,org.kordamp.gradle.java-project>>`

Configures a project with Kotlin conventions.

[[_org_kordamp_gradle_kotlin_project_tasks]]
== Tasks

[[_task_kotlin_compiler_settings]]
=== KotlinCompilerSettings

Display Kotlin compiler settings.

[horizontal]
Name:: kotlinCompilerSettings
Type:: `org.kordamp.gradle.plugin.project.kotlin.tasks.KotlinCompilerSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
task:: The task to generate the report for.
tasks:: The tasks to generate the report for.

You may specify either of the two, be advised that `tasks` has precedence over `task`. All tasks will be displayed
if neither of these options is specified.

[[_org_kordamp_gradle_kotlin_project_rules]]
== Rules

=== CompileKotlin

[horizontal]
Pattern:: compile<SourceSetName>KotlinSettings
Type:: `org.kordamp.gradle.plugin.project.kotlin.tasks.KotlinCompilerSettingsTask`
