
[[_org_kordamp_gradle_minpom]]
= Minpom

[horizontal]
id:: `org.kordamp.gradle.minpom`
class:: `org.kordamp.gradle.plugin.minpom.MinPomPlugin`
    (link:api/org/kordamp/gradle/plugin/minpom/MinPomPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/minpom/MinPomPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`

Generates a minimum POM file and a companion `pom.properties` file that are usually packaged in the main JAR produced by
the project.

== Example

For a project defined as follows

[source,groovy]
[subs="verbatim,attributes"]
.sample/build.gradle
----
plugins {
    id 'groovy'
    id 'org.kordamp.gradle.minpom' version '{project-version}'
}

group   = 'com.acme'
version = '1.0.0'

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.5.3'
}
----

Produces the following output

[source,xml]
[subs="verbatim"]
.sample/build/pom/maven/pom.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.acme</groupId>
    <artifactId>sample</artifactId>
    <version>1.0.0</version>
    <dependencies>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.5.3</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project
----

[source,java]
[subs="verbatim,attributes"]
.sample/build/pom/maven/pom.properties
----
# Generated by Gradle {gradle-version}
version=1.0.0
groupId=com.acme
artifactId=sample
----

[[_org_kordamp_gradle_minpom_dsl]]
== DSL

[source,groovy]
----
config {
    minpom {
        enabled
    }
}
----

[options="header", cols="5*"]
|===
| Name     | Type    | Required | Default Value | Description
| enabled  | boolean | no       | true          | Disables `org.kordamp.gradle.minpom` plugin if `false`
|===

This block is optional.

[[_org_kordamp_gradle_minpom_tasks]]
== Tasks

[[_task_minpom]]
=== Minpom

Generates a minimum POM file.

[horizontal]
Name:: minpom
Type:: `org.kordamp.gradle.plugin.minpom.MinpomTask`

.Properties
[horizontal]
projectArtifactId:: project.name
projectGroupId:: project.group
projectVersion:: project.version
destinationDir:: `"${project.buildDir}/pom/maven"`

