
[[_org_kordamp_gradle_publishing]]
= Publishing

[horizontal]
id:: `org.kordamp.gradle.publishing`
class:: `org.kordamp.gradle.plugin.publishing.PublishingPlugin`
    (link:api/org/kordamp/gradle/plugin/publishing/PublishingPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/publishing/PublishingPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`, +
`<<_org_kordamp_gradle_buildinfo,org.kordamp.gradle.build-info>>`, +
`<<_org_kordamp_gradle_jar,org.kordamp.gradle.jar>>`, +
`<<_org_kordamp_gradle_minpom,org.kordamp.gradle.minpom>>`, +
`<<_org_kordamp_gradle_source,org.kordamp.gradle.source-jar>>`, +
`<<_org_kordamp_gradle_javadoc,org.kordamp.gradle.javadoc>>`, +
`<<_org_kordamp_gradle_groovydoc,org.kordamp.gradle.groovydoc>>`, +
`<<_org_kordamp_gradle_apidoc,org.kordamp.gradle.apidoc>>`, +
`link:https://docs.gradle.org/current/userguide/publishing_maven.html[maven-publish]`, +
`link:https://docs.gradle.org/current/userguide/signing_plugin.html[signing]`

Configures a MavenPublication for the project's artifacts using the core `maven-publish` plugin.
The name of the publication matches `"main"`. Published artifacts include the main JAR, sources,
javadoc/groovydoc/kotlindoc JARs.

Data defined in the DSL's `config.info` and `config.license` blocks will be used to fill out information required by the
generated POM file.

[[_org_kordamp_gradle_publishing_dsl]]
== DSL

[source,groovy]
----
config {
    publishing {
        enabled
        signing
        releasesRepository
        snapshotsRepository
    }
}
----

[options="header", cols="5*"]
|===
| Name                | Type    | Required | Default Value | Description
| enabled             | boolean | no       | true          | Disables `org.kordamp.gradle.publishing` plugin if `false`
| signing             | boolean | no       | false         | Enables signing of all artifacts associated with `main`
| releasesRepository  | String  | no       |               | Name of a Maven compatible repository for publishing releases
| snapshotsRepository | String  | no       |               | Name of a Maven compatible repository for publishing snapshots
|===

This block is optional.

