
[[_org_kordamp_gradle_testing]]
= Testing

[horizontal]
id:: `org.kordamp.gradle.testing`
class:: `org.kordamp.gradle.plugin.testing.TestingPlugin`
    (link:api/org/kordamp/gradle/plugin/testing/TestingPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/testing/TestingPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`

Configures test reports.

[[_org_kordamp_gradle_testing_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    testing {
        enabled
        logging
        aggregate
        integration {
            logging
            aggregate
        }
        functional {
            logging
            aggregate
        }
    }
}
----

[options="header", cols="5*"]
|===
| Name      | Type    | Required | Default Value | Description
| enabled   | boolean | no       | true          | Disables `org.kordamp.gradle.test` plugin if `false`
| logging   | boolean | no       | true          | Enables verbose output
| aggregate | boolean | no       | true          | Enables test report aggregation
|===

[[_testing_integration]]
*integration*

[options="header", cols="5*"]
|===
| Name      | Type    | Required | Default Value | Description
| logging   | boolean | no       | true          | Enables verbose output
| aggregate | boolean | no       | true          | Enables test report aggregation
|===

[[_testing_functional]]
*functional*

[options="header", cols="5*"]
|===
| Name      | Type    | Required | Default Value | Description
| logging   | boolean | no       | true          | Enables verbose output
| aggregate | boolean | no       | true          | Enables test report aggregation
|===

[[_org_kordamp_gradle_testing_tasks]]
== Tasks

[[_task_aggregate_testing_reports]]
=== AggregateTestReports

Aggregates all test reports that are not _integration_ nor _functional_. +
This task is added to the root project.

[horizontal]
Name:: aggregateTestReports
Type:: `org.gradle.api.tasks.testing.TestReport`

.Properties
[horizontal]
destinationDir:: `${rootProject.buildDir}/reports/aggregate-tests`

[[_task_aggregate_integration_testing_reports]]
=== AggregateIntegrationTestReports

Aggregates all integration test reports. +
This task is added to the root project.

[horizontal]
Name:: aggregateIntegrationTestReports
Type:: `org.gradle.api.tasks.testing.TestReport`

.Properties
[horizontal]
destinationDir:: `${rootProject.buildDir}/reports/aggregate-integration-tests`

[[_task_aggregate_functional_testing_reports]]
=== AggregateFunctionalTestReports

Aggregates all functional test reports. +
This task is added to the root project.

[horizontal]
Name:: aggregateFunctionalTestReports
Type:: `org.gradle.api.tasks.testing.TestReport`

.Properties
[horizontal]
destinationDir:: `${rootProject.buildDir}/reports/aggregate-fiunctional-tests`

[[_task_aggregate_all_testing_reports]]
=== AggregateAllTestReports

Aggregates all test reports. +
This task is added to the root project.

[horizontal]
Name:: aggregateAllTestReports
Type:: `org.gradle.api.tasks.testing.TestReport`

.Properties
[horizontal]
destinationDir:: `${rootProject.buildDir}/reports/aggregate-all-tests`


