
[[_org_kordamp_gradle_test]]
= Test

[horizontal]
id:: `org.kordamp.gradle.test`
class:: `org.kordamp.gradle.plugin.test.TestPlugin`
    (link:api/org/kordamp/gradle/plugin/test/TestPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/test/TestPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`

Configures test reports.

[[_org_kordamp_gradle_test_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    test {
        enabled
        logging
        aggregate
        integration {
            logging
            aggregate
        }
        functional {
            logging
            aggregate
        }
    }
}
----

[options="header", cols="5*"]
|===
| Name      | Type    | Required | Default Value | Description
| enabled   | boolean | no       | true          | Disables `org.kordamp.gradle.test` plugin if `false`
| logging   | boolean | no       | true          | Enables verbose output
| aggregate | boolean | no       | true          | Enables test report aggregation
|===

[[_test_integration]]
*integration*

[options="header", cols="5*"]
|===
| Name      | Type    | Required | Default Value | Description
| logging   | boolean | no       | true          | Enables verbose output
| aggregate | boolean | no       | true          | Enables test report aggregation
|===

[[_test_functional]]
*functional*

[options="header", cols="5*"]
|===
| Name      | Type    | Required | Default Value | Description
| logging   | boolean | no       | true          | Enables verbose output
| aggregate | boolean | no       | true          | Enables test report aggregation
|===

[[_org_kordamp_gradle_test_tasks]]
== Tasks

[[_task_aggregate_test_reports]]
=== AggregateTestReports

Aggregates all test reports that are not _integration_ nor _functional_. +
This task is added to the root project.

[horizontal]
Name:: aggregateTestReports
Type:: `org.gradle.api.tasks.testing.TestReport`

.Properties
[horizontal]
destinationDir:: `${project.buildDir}/reports/aggregate-tests`

[[_task_aggregate_integration_test_reports]]
=== AggregateIntegrationTestReports

Aggregates all integration test reports. +
This task is added to the root project.

[horizontal]
Name:: aggregateIntegrationTestReports
Type:: `org.gradle.api.tasks.testing.TestReport`

.Properties
[horizontal]
destinationDir:: `${project.buildDir}/reports/aggregate-integration-tests`

[[_task_aggregate_functional_test_reports]]
=== AggregateFunctionalTestReports

Aggregates all functional test reports. +
This task is added to the root project.

[horizontal]
Name:: aggregateFunctionalTestReports
Type:: `org.gradle.api.tasks.testing.TestReport`

.Properties
[horizontal]
destinationDir:: `${project.buildDir}/reports/aggregate-fiunctional-tests`

[[_task_aggregate_all_test_reports]]
=== AggregateAllTestReports

Aggregates all test reports. +
This task is added to the root project.

[horizontal]
Name:: aggregateAllTestReports
Type:: `org.gradle.api.tasks.testing.TestReport`

.Properties
[horizontal]
destinationDir:: `${project.buildDir}/reports/aggregate-all-tests`


