
[[_org_kordamp_gradle_base]]
= Base

[horizontal]
id:: `org.kordamp.gradle.base`
class:: `org.kordamp.gradle.plugin.base.BasePlugin`
    (link:api/org/kordamp/gradle/plugin/base/BasePlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/base/BasePlugin.html[source])
applied by:: `<<_org_kordamp_gradle_bintray,org.kordamp.gradle.bintray>>`, +
`<<_org_kordamp_gradle_bom,org.kordamp.gradle.bom>>`, +
`<<_org_kordamp_gradle_buildinfo,org.kordamp.gradle.build-info>>`, +
`<<_org_kordamp_gradle_checkstyle,org.kordamp.gradle.chekcstyle>>`, +
`<<_org_kordamp_gradle_clirr,org.kordamp.gradle.clirr>>`, +
`<<_org_kordamp_gradle_codenarc,org.kordamp.gradle.codenarc>>`, +
`<<_org_kordamp_gradle_coveralls,org.kordamp.gradle.coveralls>>`, +
`<<_org_kordamp_gradle_cpd,org.kordamp.gradle.cpd>>`, +
`<<_org_kordamp_gradle_detekt,org.kordamp.gradle.detekt>>`, +
`<<_org_kordamp_gradle_errorprone,org.kordamp.gradle.errorprone>>`, +
`<<_org_kordamp_gradle_functionaltest,org.kordamp.gradle.functional-test>>`, +
`<<_org_kordamp_gradle_groovydoc,org.kordamp.gradle.groovydoc>>`, +
`<<_org_kordamp_gradle_guide,org.kordamp.gradle.guide>>`, +
`<<_org_kordamp_gradle_integrationtest,org.kordamp.gradle.integration-test>>`, +
`<<_org_kordamp_gradle_jacoco,org.kordamp.gradle.jacoco>>`, +
`<<_org_kordamp_gradle_jar,org.kordamp.gradle.jar>>`, +
`<<_org_kordamp_gradle_javadoc,org.kordamp.gradle.javadoc>>`, +
`<<_org_kordamp_gradle_kotlindoc,org.kordamp.gradle.kotlindoc>>`, +
`<<_org_kordamp_gradle_licensing,org.kordamp.gradle.licensing>>`, +
`<<_org_kordamp_gradle_minpom,org.kordamp.gradle.minpom>>`, +
`<<_org_kordamp_gradle_plugins,org.kordamp.gradle.plugin>>`, +
`<<_org_kordamp_gradle_pmd,org.kordamp.gradle.pmd>>`, +
`<<_org_kordamp_gradle_project,org.kordamp.gradle.project>>`, +
`<<_org_kordamp_gradle_publishing,org.kordamp.gradle.publishing>>`, +
`<<_org_kordamp_gradle_scaladoc,org.kordamp.gradle.scaladoc>>`, +
`<<_org_kordamp_gradle_sonar,org.kordamp.gradle.sonar>>`, +
`<<_org_kordamp_gradle_source,org.kordamp.gradle.source-jar>>`, +
`<<_org_kordamp_gradle_sourcehtml,org.kordamp.gradle.source-html>>`, +
`<<_org_kordamp_gradle_sourcexref,org.kordamp.gradle.source-xref>>`, +
`<<_org_kordamp_gradle_sourcestats,org.kordamp.gradle.source-stats>>`, +
`<<_org_kordamp_gradle_spotbugs,org.kordamp.gradle.spotbugs>>`, +
`<<_org_kordamp_gradle_testing,org.kordamp.gradle.testing>>`

Enables the configuration DSL. Settings made via this DSL are consumed by multiple plugins.

[[_org_kordamp_gradle_base_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    release

    <<_base_info,info>> {
        name
        description
        inceptionYear
        vendor
        tags

        <<_base_info_links,links>> {
            enabled
            website
            issueTracker
            scm
        }

        <<_base_info_scm,scm>> {
            enabled
            url
            tag
            connection
            developerConnection
        }

        <<_base_info_organization,organization>> {
            name
            url
        }

        <<_base_info_specification,specification>> {
            enabled
            title
            version
            vendor
        }

        <<_base_info_implementation,implementation>> {
            enabled
            title
            version
            vendor
            vendorId
            vendorUrl
        }

        <<_base_info_credentials,credentials>> {
            inherits
            mergeStrategy
            github {
                username
                password
            }
            sonatype {
                username
                password
            }
            named {
                name
                username
                password
            }
        }

        <<_base_info_repositories,repositories>> {
            inherits
            mergeStrategy
            <<_base_info_repository,repository>> {
                name
                url
                credentials {
                    username
                    passsword
                }
            }
        }

        <<_base_info_people,people>> {
            inherits
            mergeStrategy
            <<_base_info_person,person>> {
                id
                name
                email
                url
                roles
                timezone
                <<_base_info_organization,organization>> {
                    name
                    url
                }
                properties
            }
        }

        <<_base_info_issueManagement,issueManagement>> {
            system
            url
        }

        <<_base_info_ciManagement,ciManagement>> {
            system
            url
        }

        <<_base_info_mailingLists,mailingLists>> {
            inherits
            mergeStrategy
            <<_base_info_mailingList,mailingList>> {
                name
                subscribe
                unsubscribe
                post
                archive
                otherArchives
            }
        }
    }

    <<_base_dependencyManagement,dependencyManagement>> {
        dependency(String)
    }
}
----

The `release` flag should be set to `true` (default is `false`) when a release (any kind of release, even snapshot) is
needed. At the moment this flag controls enrichment of JAR manifests as explained in the <<_org_kordamp_gradle_jar,Jar>>
plugin. Other plugins may hook into this flag to provide additional configuration and behavior.

[[_base_info]]
*general*

[options="header", cols="5*"]
|===
| Name          | Type         | Required | Default Value | Description
| name          | String       | no       | project.name  | Mapped to the `<name>` block in POM
| description   | String       | yes      |               | Mapped to the `<description>` block in POM
| inceptionYear | String       | no       | current year  | Mapped to the `<inceptionYear>` block in POM
| vendor        | String       | no*      |               |
| tags          | List<String> | no       | []            |
|===

The value for `vendor` may be omitted if a value for `organization.name` is given.

[[_base_info_links]]
*links*

[options="header", cols="5*"]
|===
| Name         | Type    | Required | Default Value | Description
| enabled      | boolean | no       | true          | Enables or disables this block.
| website      | String  | yes      | empty         | Mapped to the `<url>` block in POM.
                                                      Mapped to `bintray.pkg.websiteUrl`
| issueTracker | String  | no*      | empty         | Mapped to `bintray.pkg.issueTracker`
| scm          | String  | no*      | empty         | Mapped to the `<scm>` block in POM.
                                                      Mapped to `bintray.pkg.websiteUrl`
|===

Values for `issueTracker` and `scm` should be defined if the `<<_org_kordamp_gradle_bintray,org.kordamp.gradle.bintray>>`
plugin is used.

[[_base_info_scm]]
*scm*

[options="header", cols="5*"]
|===
| Name                | Type    | Required | Default Value | Description
| enabled             | boolean | no       | true          | Enables or disables this block.
| url                 | String  | yes      | empty         | Mapped to the `<scm><url>` block in POM.OM.
| connection          | String  | no*      | empty         | Mapped to the `<scm><connection>` block in POM.`
| developerconnection | String  | no*      | empty         | Mapped to the `<scm><developerConnection>` block in POM.
|===

This block has precedence over `links.scm`.

[[_base_info_organization]]
*organization*

[options="header", cols="5*"]
|===
| Name | Type   | Required | Default Value | Description
| name | String | no       |               | The name of the organization
| url  | String | no       |               | The URL of the organization (website perhaps).
|===

This block is optional.

[[_base_info_specification]]
*specification*

[options="header", cols="5*"]
|===
| Name    | Type    | Required | Default Value   | Description
| enabled | boolean | no       | true            | JAR manifest entries will be updated if `true`
| title   | String  | no       | project.name    | Mapped to `Specification-Title` manifest entry
| version | String  | no       | project.version | Mapped to `Specification-Version` manifest entry
| vendor  | String  | no       | info.vendor     | Mapped to `Specification-Vendor` manifest entry
|===

This block is optional.

[[_base_info_implementation]]
*implementation*

[options="header", cols="5*"]
|===
| Name     | Type    | Required | Default Value   | Description
| enabled  | boolean | no       | true            | JAR manifest entries will be updated if `true`
| title    | String  | no       | project.name    | Mapped to `Implementation-Title` manifest entry
| version  | String  | no       | project.version | Mapped to `Implementation-Version` manifest entry
| vendor   | String  | no       | info.vendor     | Mapped to `Implementation-Vendor` manifest entry
| vendorId | String  | no       |                 | Mapped to `Implementation-Vendor-Id` manifest entry
| url      | String  | no       |                 | Mapped to `Implementation-Url` manifest entry
|===

This block is optional.

[[_base_info_credentials]]
*credentials*

[options="header", cols="5*"]
|===
| Name          | Type          | Required | Default Value | Description
| github        | Credentials   | no*      |               | Username/Password for connecting to GitHub
| sonatype      | Credentials   | no*      |               | Username/Password for connecting to Maven Central
| named         | Credentials   | no*      |               | Defines a named credentials entry. Name may match a repository entry.
| inherits      | boolean       | no       | true          | Whether to inherit values from a parent `POM`.
| mergeStrategy | MergeStrategy | no       | UNIQUE        | One of `PREPEND`, `APPEND`, `UNIQUE`, `OVERWRITE`.
|===

The value of `inherits` cannot be changed once it has been set.

The values of `mergeStrategy` control how multiple credentials will be handled

[horizontal]
PREPEND:: Child values (if any) will be placed before inherited values (if any).
APPEND:: Child values (if any) will be placed after inherited values (if any).
UNIQUE:: Child and inherited values will be merged by license id.
OVERWRITE:: Child values will be used unless empty, in which case inherited values will be used.

The `sonatype` entry may be used by the `<<_org_kordamp_gradle_bintray,org.kordamp.gradle.bintray>>` plugin to configure
auto-sync with Maven Central when pushing a publication. Named credentials my match the name of a repository, in which
case they will be used during artifact publication on the matching repository.

This block is optional.

[[_base_info_repositories]]
*repositories*

This block defines data associated with a particular repository. Entries may be used during publication.

[options="header", cols="5*"]
|===
| Name          | Type          | Required | Default Value | Description
| inherits      | boolean       | no       | true          | Whether to inherit values from a parent `POM`.
| mergeStrategy | MergeStrategy | no       | UNIQUE        | One of `PREPEND`, `APPEND`, `UNIQUE`, `OVERWRITE`.
|===

The value of `inherits` cannot be changed once it has been set.

The values of `mergeStrategy` control how multiple repositories will be handled

[horizontal]
PREPEND:: Child values (if any) will be placed before inherited values (if any).
APPEND:: Child values (if any) will be placed after inherited values (if any).
UNIQUE:: Child and inherited values will be merged by license id.
OVERWRITE:: Child values will be used unless empty, in which case inherited values will be used.

[[_base_info_repository]]
*repository*

[options="header", cols="5*"]
|===
| Name        | Type        | Required | Default Value | Description
| name        | String      | no*      |               | The name of the repository
| url         | String      | no*      |               | The URL of the repository
| credentials | Credentials | no*      |               | Values mapped to `credentials` block
|===

The `credentials` entry is optional. Credentials may be defined locally to the repository or globally using the
<<_base_info_credentials,credentials>> block. Local credentials have precedence over global credentials that match
the repository name.

[[_base_info_people]]
*people*

[options="header", cols="5*"]
|===
| Name          | Type          | Required | Default Value | Description
| inherits      | boolean       | no       | true          | Whether to inherit values from a parent `POM`.
| mergeStrategy | MergeStrategy | no       | UNIQUE        | One of `PREPEND`, `APPEND`, `UNIQUE`, `OVERWRITE`.
|===

The value of `inherits` cannot be changed once it has been set.

The values of `mergeStrategy` control how multiple people will be handled

[horizontal]
PREPEND:: Child values (if any) will be placed before inherited values (if any).
APPEND:: Child values (if any) will be placed after inherited values (if any).
UNIQUE:: Child and inherited values will be merged by license id.
OVERWRITE:: Child values will be used unless empty, in which case inherited values will be used.

This block defines data associated with a particular person.

This block is optional if none of the following plugins are used: `<<_org_kordamp_gradle_javadoc,org.kordamp.gradle.javadoc>>`,
`<<_org_kordamp_gradle_groovydoc,org.kordamp.gradle.groovydoc>>`,
`<<_org_kordamp_gradle_publishing,org.kordamp.gradle.publishing>>`, `<<_org_kordamp_gradle_bintray,org.kordamp.gradle.bintray>>`.

[[_base_info_person]]
*person*

[options="header", cols="5*"]
|===
| Name         | Type                | Required | Default Value | Description
| id           | String              | no*      |               | Mapped to the `<id>` block in POM
| name         | String              | no*      |               | Mapped to the `<name>` block in POM
| email        | String              | no       |               | Mapped to the `<email>` block in POM
| url          | String              | no       |               | Mapped to the `<url>` block in POM
| organization | Organization        | no       |               | Mapped to the `<organizationName>` and `<organizationUrl>` blocks in POM
| roles        | List<String>        | no       |               | Mapped to the `<roles>` block in POM
| timezone     | String              | no       |               | Mapped to the `<timezone>` block in POM
| properties   | Map<String, Object> | no       | [:]           | Mapped to the `<properties>` block in POM
|===

At least `id` or `name` must be defined. If a `developer` role exists then the person instance is mapped to a `<developer>`
block in the POM. If a `contributor` role exists then the person instance is maped to a `<contributor>` block in the POM.

[[_base_info_issueManagement]]
*issueManagement*

[options="header", cols="5*"]
|===
| Name        | Type        | Required | Default Value | Description
| system      | String      | no       |               | The system value of the `<issueManagement>` block in POM
| url         | String      | no       |               | The url value of the `<issueManagement>` block in POM
|===

[[_base_info_ciManagement]]
*ciManagement*

[options="header", cols="5*"]
|===
| Name        | Type        | Required | Default Value | Description
| system      | String      | no       |               | The system value of the `<ciManagement>` block in POM
| url         | String      | no       |               | The url value of the `<ciManagement>` block in POM
|===

[[_base_info_mailingLists]]
*mailingLists*

[options="header", cols="5*"]
|===
| Name          | Type          | Required | Default Value | Description
| inherits      | boolean       | no       | true          | Whether to inherit values from a parent `POM`.
| mergeStrategy | MergeStrategy | no       | UNIQUE        | One of `PREPEND`, `APPEND`, `UNIQUE`, `OVERWRITE`.
|===

The value of `inherits` cannot be changed once it has been set.

The values of `mergeStrategy` control how multiple mailing lists will be handled

[horizontal]
PREPEND:: Child values (if any) will be placed before inherited values (if any).
APPEND:: Child values (if any) will be placed after inherited values (if any).
UNIQUE:: Child and inherited values will be merged by license id.
OVERWRITE:: Child values will be used unless empty, in which case inherited values will be used.

This block defines a list of MailingList entries.

[[_base_info_mailingList]]
*mailingList*

[options="header", cols="5*"]
|===
| Name          | Type         | Required | Default Value | Description
| name          | String       | no*      |               | Mapped to the `<name>` block in POM
| subscribe     | String       | no       |               | Mapped to the `<subscribe>` block in POM
| unsubscribe   | String       | no       |               | Mapped to the `<unsubscribe>` block in POM
| post          | String       | no       |               | Mapped to the `<post>` block in POM
| archive       | String       | no       |               | Mapped to the `<archive>` block in POM
| otherArchives | List<String> | no       |               | Mapped to the `<otherArchives>` block in POM
|===

At least `name` must be defined.

[[_base_dependencyManagement]]
*dependencyManagement*

This block serves as a central point for declaring dependencies and platforms that can later be reused in other places
such as the standard `dependencies` block. Dependency definitions require 4 elements:

[horizontal]
name:: short name of the dependency or platform.
groupId:: the groupId part of the artifact's coordinates.
artifactId:: the artifactId part of the artifact's coordinates.
version:: the version part of the artifact's coordinates.
platform:: `true` if this dependency constitutes a platform, `false` otherwise (default).

Additionally a dependency may define a set of modules that go together, for example, for `groovy` you can have the
`grovy-core`, `groovy-xml`, `groovy-json` modules. All modules and the owning dependency share the same `groupId` and `version`.

The `dependencyManagement` block will suggest/force dependency versions for all configurations. You can disable this feature
by defining a System property `org.kordamp.gradle.base.dependency.management` with `false` as value.

WARNING: This feature ships in preview mode and is disabled by default.

WARNING: Dependencies defined in the `dependencyManagement` block cannot have classifiers and must be resolvable from a Maven compatible repository.

[[_org_kordamp_gradle_base_dependencyManagement_methods]]
=== Methods

dependency(String gavNotation):: Defines a dependency. Argument must use the `groupId:artifactId:version` notation. Dependency name will be equal to `artifactId`. +
Example: +
[source,groovy]
----
dependency('com.googlecode.guava:guava:29.0-jre')
----
dependency(String name, String gavNotation):: Defines a dependency. Second argument must use the `groupId:artifactId:version` notation. +
Example: +
[source,groovy]
----
dependency('guava', 'com.googlecode.guava:guava:29.0-jre')
----
dependency(String name, String gavNotation, Action action):: Defines and configures a dependency. Second argument must use the `groupId:artifactId:version` notation. +
Example: +
[source,groovy]
----
dependency('groovy', 'org.codehaus.groovy:groovy:3.0.6') {
    modules = [
        'groovy-test',
        'groovy-json',
        'groovy-xml'
    ]
}
----
dependency(String name, String gavNotation, Closure action):: Defines and configures a dependency. Second argument must use the `groupId:artifactId:version` notation. +
Example: +
[source,groovy]
----
dependency('groovy', 'org.codehaus.groovy:groovy:3.0.6') {
    modules = [
        'groovy-test',
        'groovy-json',
        'groovy-xml'
    ]
}
----
platform(String gavNotation):: Defines a platform dependency. Argument must use the `groupId:artifactId:version` notation. Dependency name will be equal to `artifactId`. +
Example: +
[source,groovy]
----
platform('io.micronaut:micronaut-bom:2.0.2')
----
platform(String name, String gavNotation):: Defines a platform dependency. Second argument must use the `groupId:artifactId:version` notation. +
Example: +
[source,groovy]
----
platform('micronaut', 'io.micronaut:micronaut-bom:2.0.2')
----
dependency(String gavNotation, Action action):: Defines and configures a dependency by name. +
Example: +
[source,groovy]
----
dependency('org.codehaus.groovy:groovy:3.0.6') {
    modules = [
        'groovy-test',
        'groovy-json',
        'groovy-xml'
    ]
}
----
dependency(String gavNotation, Closure action):: Defines and configures a dependency by name. +
Example: +
[source,groovy]
----
dependency('org.codehaus.groovy:groovy:3.0.6') {
    modules = [
        'groovy-test',
        'groovy-json',
        'groovy-xml'
    ]
}
----
getDependency(String name):: Returns the named dependency (if it exists). Throws an exception otherwise. +
The `name` parameter may be the logical name or the `groupId:artifactId` of the dependency. +
Example: +
[source,groovy]
----
getDependency('guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
getDependency('com.googlecode.guava:guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
----
findDependency(String nameOrGa):: Finds a dependency by name or GA if it exists, `null` otherwise. +
Example: +
[source,groovy]
----
findDependency('guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
findDependency('com.googlecode.guava:guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
----
findDependencyByName(String name):: Finds a dependency by name if it exists, `null` otherwise. +
Example: +
[source,groovy]
----
findDependencyByName('guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
----
findDependencyByGA(String name, String moduleNAme):: Finds a dependency by groupId and artifactId if it exists, `null` otherwise. +
Example: +
[source,groovy]
----
findDependencyByGA('com.googlecode.guava', 'guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
----
getPlatform(String name):: Returns the named platform (if it exists). Throws an exception otherwise. +
The `name` parameter may be the logical name or the `groupId:artifactId` of the platform. +
Example: +
[source,groovy]
----
getPlatform('micronaut') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
getPlatform('io.micronaut:micronaut-bom') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
----
findPlatform(String nameOrGa):: Returns the named platform (if it exists).
The `nameOrGa` parameter may be the logical name or the `groupId:artifactId` of the platform. +
Example: +
[source,groovy]
----
findPlatform('micronaut') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
findPlatform('io.micronaut:micronaut-bom') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
----
findPlatformByName(String name):: Finds a platform by name if it exists, `null` otherwise. +
Example: +
[source,groovy]
----
findPlatformByName('micronaut') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
----
findPlatformByGA(String name, String moduleNAme):: Finds a platform by groupId and artifactId if it exists, `null` otherwise. +
Example: +
[source,groovy]
----
findPlatformByGA('io.micronaut', 'micronaut-bom') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
----
gav(String name):: Returns the given dependency in GAV notation if it exists. Throws an exception otherwise. +
The `name` parameter may be the logical name or the `groupId:artifactId` of the dependency. +
Example: +
[source,groovy]
----
gav('groovy') == 'org.codehaus.groovy:groovy:3.0.6'
gav('org.codehaus.groovy:groovy') == 'org.codehaus.groovy:groovy:3.0.6'
----
gav(String name, String moduleName):: Returns the given module dependency in GAV notation if it exists. Throws an exception otherwise. +
The `name` parameter may be the logical name or the `groupId:artifactId` of the dependency. +
Example: +
[source,groovy]
----
gav('groovy', 'groovy-json') == 'org.codehaus.groovy:groovy-json:3.0.6'
gav('org.codehaus.groovy:groovy', 'groovy-json') == 'org.codehaus.groovy:groovy-json:3.0.6'
----
ga(String name, String moduleName):: Returns the given module dependency in GA (groupId/artifactId) notation if it exists. Throws an exception otherwise. +
The `name` parameter may be the logical name or the `groupId:artifactId` of the dependency. +
Example: +
[source,groovy]
----
ga('micronaut', 'micronaut-core') == 'io.micronaut:micronaut-core'
ga('io.micronaut:micronaut-bom', 'micronaut-core') == 'io.micronaut:micronaut-core'
----

WARNING: Instances of type `org.kordamp.gradle.plugin.base.model.artifact.Dependency` or `org.kordamp.gradle.plugin.base.model.artifact.Platform`
can not be passed directly to Gradle's dependency resolution mechanism. You must convert them to any of the accepted
notations such as `groupId:artifactId:version`, use the `gav()` or `ga()` utility methods instead.

==== Example

[source,groovy]
.build.gradle
----
config {
    dependencyManagement {
        // a dependency with modules
        dependency('groovy') {
            groupId    = 'org.codehaus.groovy'
            artifactId = 'groovy'
            version    = '3.0.6'
            modules    = [
                'groovy-test',
                'groovy-json',
                'groovy-xml'
            ]
        }
        // a dependency without modules
        dependency('junit:junit:4.13')
        // a platform
        platform('micronaut', 'io.micronaut:micronaut-bom:2.0.2')
    }
}
----

These dependencies can be used in combination with the <<_org_kordamp_gradle_java_project_extension_applyToDefaults,applyToDefaults>>
and  <<_org_kordamp_gradle_java_project_extension_applyTo,applyTo>> extensions if the
`<<_org_kordamp_gradle_java_project,org.kordamp.gradle.java-project>>` plugin is applied, for example

[source,groovy]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.java-project'
}

config {
    dependencyManagement {
        // a dependency with modules
        dependency('groovy') {
            groupId    = 'org.codehaus.groovy'
            artifactId = 'groovy'
            version    = '3.0.6'
            modules    = [
                'groovy-test',
                'groovy-json',
                'groovy-xml'
            ]
        }
        // a dependency without modules
        dependency('junit:junit:4.13')
        // a platform
        platform('micronaut', 'io.micronaut:micronaut-bom:2.0.2')
    }
}

// consume dependencies
dependencies {
    // apply Micronaut platform to some configurations
    applyTo.c('api', 'annotationProcessor', 'compileOnly').platform('micronaut')
    // configure a dependency in the standard way
    api 'io.micronaut:micronaut-core'
    // configure a platform module by groupId:artifactId
    annotationProcessor config.dependencyManagement.ga('micronaut', 'micronaut-inject')
    // pull in a module from Groovy
    api config.dependencyManagement.gav('groovy', 'groovy-json')
    // configure a single dependency
    testImplementation config.dependencyManagement.gav('junit')
}
----

Will generate the following entries in the POM if publishing is enabled

[source,xml,subs="verbatim"]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <!--
    coordinates and other elements omitted for brevity
   -->
  <properties>
    <micronaut.version>2.0.2</micronaut.version>
    <groovy.version>3.0.6</groovy.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.micronaut</groupId>
        <artifactId>micronaut-bom</artifactId>
        <version>${micronaut.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-json</artifactId>
      <version>${groovy.version}</version>
    </dependency>
  </dependencies>
</project>
----

[[_org_kordamp_gradle_base_sysprops]]
=== System Properties

org.kordamp.gradle.base.validate:: Perform validation on DSL settings. Defaults to `true`.
org.kordamp.gradle.base.dependency.management:: Suggest/force dependency versions. Defaults to `false`.

[[_org_kordamp_gradle_base_tasks]]
== Tasks

[[_task_archives]]
=== Archives

Displays all configured archives in a project.

[horizontal]
Name:: archives
Type:: `org.kordamp.gradle.plugin.base.tasks.ArchivesTask`

==== Example Output

For a project defined as follows

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'java-library'
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    info {
        description      = 'Demo project'
        vendor           = 'Acme'
        links.scm        = 'https://github.com/acme/demo'
        organization.url = 'https://github.com/acme'
    }
    licensing  { enabled = false }
}

----

Invoking these command

[source]
----
$ gm :archives
----

Results in the following output

[source]
----
> Task :archives
Total archives: 2

artifact 0
    name: demo
    type: jar
    extension: jar
    date: Sun Jan 24 14:30:57 CET 2021
    file: /tmp/demo/build/libs/demo.jar
artifact 1
    name: demo
    type: jar
    extension: jar
    classifier: javadoc
    date: Sun Jan 24 14:30:57 CET 2021
    file: /tmp/demo/build/libs/demo-javadoc.jar
----

[[_task_clear_kordamp_file_cache]]
=== ClearKordampFileCache

Clears the Kordamp file cache.

[horizontal]
Name:: clearKordampFileCache
Type:: `org.kordamp.gradle.plugin.base.tasks.ClearKordampFileCacheTask`

[[_task_configurations]]
=== Configurations

Displays all configurations available in a project.

[horizontal]
Name:: configurations
Type:: `org.kordamp.gradle.plugin.base.tasks.ConfigurationsTask`

==== Example Output

For a project defined as follows

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'java-library'
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

Invoking these command

[source]
----
$ gm :configurations
----

Results in the following output

[source]
----
> Task :configurations
Total configurations: 25

configuration 0:
    name: annotationProcessor

configuration 1:
    name: apiElements

configuration 2:
    name: archives

configuration 3:
    name: compile

configuration 4:
    name: compileClasspath

configuration 5:
    name: compileOnly

configuration 6:
    name: default

configuration 7:
    name: implementation

configuration 8:
    name: jacocoAgent

configuration 9:
    name: jacocoAnt

configuration 10:
    name: java2html

configuration 11:
    name: runtime

configuration 12:
    name: runtimeClasspath

configuration 13:
    name: runtimeElements

configuration 14:
    name: runtimeOnly

configuration 15:
    name: signatures

configuration 16:
    name: sourcesElements

configuration 17:
    name: testAnnotationProcessor

configuration 18:
    name: testCompile

configuration 19:
    name: testCompileClasspath

configuration 20:
    name: testCompileOnly

configuration 21:
    name: testImplementation

configuration 22:
    name: testRuntime

configuration 23:
    name: testRuntimeClasspath

configuration 24:
    name: testRuntimeOnly
----

[[_task_configuration_settings]]
=== ConfigurationSettings

Display settings of a Configuration

[horizontal]
Name:: configurationSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.ConfigurationSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
configuration:: The configuration to generate the report for.
configurations:: The configurations to generate the report for.

You may specify either of the two, be advised that `configurations` has precedence over `configuration`. All configurations will be displayed
if neither of these options is specified.

[[_task_effective_settings]]
=== EffectiveSettings

Displays resolved settings

[horizontal]
Name:: effectiveSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.EffectiveSettingsTask`

.Options
[horizontal]
section:: The section to generate the report for.
sections:: The sections to generate the report for.
show-secrets:: Show secret values instead of masked values. Value masking is applied to properties that contain any
of the following words: `secret`, `password`, `credential`, `token`, `apikey`, `login`. The list of words can be overridden by
setting a System property named `kordamp.secret.keywords` to a comma delimited String, such as `password,secret`.

You may specify either of the two, be advised that `sections` has precedence over `section`. All sections will be displayed
if neither of these options is specified. Section names match entries found in the <<_config_dsl,DSL>>.

[[_task_extensions]]
=== Extensions

Displays all extensions applied to a project

[horizontal]
Name:: effectiveSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.ExtensionsTask`

==== Example Output

For a project defined as follows

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

Invoking these command

[source]
----
$ gm :extensions
----

Results in the following output

[source]
----
> Task :extensions
Total extensions: 12

extension 0:
    name: ext
    type: org.gradle.api.plugins.ExtraPropertiesExtension

extension 1:
    name: defaultArtifacts
    type: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet

extension 2:
    name: config
    type: org.kordamp.gradle.plugin.base.ProjectConfigurationExtension

extension 3:
    name: projects
    type: org.kordamp.gradle.plugin.base.ProjectsExtension

extension 4:
    name: profiles
    type: org.kordamp.gradle.plugin.profiles.ProfilesExtension

extension 5:
    name: reporting
    type: org.gradle.api.reporting.ReportingExtension

extension 6:
    name: downloadLicenses
    type: nl.javadude.gradle.plugins.license.DownloadLicensesExtension

extension 7:
    name: license
    type: nl.javadude.gradle.plugins.license.LicenseExtension

extension 8:
    name: jacoco
    type: org.gradle.testing.jacoco.plugins.JacocoPluginExtension

extension 9:
    name: coveralls
    type: org.kt3k.gradle.plugin.CoverallsPluginExtension

extension 10:
    name: signing
    type: org.gradle.plugins.signing.SigningExtension

extension 11:
    name: versioning
    type: net.nemerosa.versioning.VersioningExtension
----

[[_task_extension_settings]]
=== ExtensionSettings

Display settings of an Extension

[horizontal]
Name:: extensionSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.ExtensionSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
extension:: The extension to generate the report for.
extensions:: The extensions to generate the report for.

You may specify either of the two, be advised that `extensions` has precedence over `extension`. All extensions will be displayed
if neither of these options is specified.

[[_task_list_included_builds]]
=== ListIncludedBuilds

Lists all included builds in this project

[horizontal]
Name:: listIncludedBuilds
Type:: `org.kordamp.gradle.plugin.base.tasks.ListIncludedBuildsTask`

==== Example Output

For a project defined as follows

[source,groovy]
----
.
├── build.gradle
└── settings.gradle
----

[source,groovy,subs="verbatim,attributes"]
.settings.gradle
----
includeBuild '../build1'
includeBuild '../build2'
----

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

Invoking these command

[source]
----
$ gm :listIncludedBuilds
----

Results in the following output

[source]
----
> Task :listIncludedBuilds
Total included builds: 2

build1:
    projectDir: /tmp/build1

build12:
    projectDir: /tmp/build2
----

[[_task_list_projects]]
=== ListProjects

Lists all projects

[horizontal]
Name:: listProjects
Type:: `org.kordamp.gradle.plugin.base.tasks.ListProjectsTask`

.Options
[horizontal]
absolute:: Should paths be printed as absolutes or not. Defaults to `false`.

==== Example Output

For a project defined as follows

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
└── subprojects
    ├── project1
    │   ├── project1.gradle
    └── project2
        └── project2.gradle
----

[source,groovy,subs="verbatim,attributes"]
.settings.gradle
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.kordamp.gradle:settings-gradle-plugin:{project-version}'
    }
}
apply plugin: 'org.kordamp.gradle.settings'
----

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

[source,groovy,subs="verbatim,attributes"]
.subprojects/project1.gradle
----
apply plugin: 'java'
----

[source,groovy,subs="verbatim,attributes"]
.subprojects/project2.gradle
----
apply plugin: 'java'
----

Invoking these command

[source]
----
$ gm :listProjects
----

Results in the following output

[source]
----
> Task :listProjects
Total projects: 3

sample:
    root: true
    path: :
    projectDir: /tmp/sample
    buildFile: /tmp/sample/build.gradle
    buildDir: /tmp/sample/build
 
project1:
    path: :project1
    projectDir: subprojects/project1
    buildFile: subprojects/project1/project1.gradle
    buildDir: subprojects/project1/build
 
project2:
    path: :project2
    projectDir: subprojects/project2
    buildFile: subprojects/project2/project2.gradle
    buildDir: subprojects/project2/build
----

[[_task_package]]
=== Package

Assembles the outputs of the project. This is an alias for `assemble`.

[horizontal]
Name:: assemble
Type:: `org.gradle.api.DefaultTask`

[[_task_plugins]]
=== Plugins

Displays all plugins applied to a project

[horizontal]
Name:: plugins
Type:: `org.kordamp.gradle.plugin.base.tasks.PluginsTask`

==== Example Output

For a project defined as follows

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

Invoking these command

[source]
----
$ gm :plugins
----

Results in the following output

[source,subs="verbatim,attributes"]
----
> Task :plugins
Total plugins: 30

plugin 0:
    id: help-tasks
    version: {gradle-version}
    implementationClass: org.gradle.api.plugins.HelpTasksPlugin

plugin 1:
    id: build-init
    version: {gradle-version}
    implementationClass: org.gradle.buildinit.plugins.BuildInitPlugin

plugin 2:
    id: wrapper
    version: {gradle-version}
    implementationClass: org.gradle.buildinit.plugins.WrapperPlugin

plugin 3:
    id: lifecycle-base
    version: {gradle-version}
    implementationClass: org.gradle.language.base.plugins.LifecycleBasePlugin

plugin 4:
    id: base
    version: {gradle-version}
    implementationClass: org.gradle.api.plugins.BasePlugin

plugin 5:
    id: org.kordamp.gradle.base
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.base.BasePlugin
    enabled: true

plugin 6:
    id: org.kordamp.gradle.profiles
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.profiles.ProfilesPlugin
    enabled: true

plugin 7:
    id: org.kordamp.gradle.build-info
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.buildinfo.BuildInfoPlugin
    enabled: true

plugin 8:
    id: reporting-base
    version: {gradle-version}
    implementationClass: org.gradle.api.plugins.ReportingBasePlugin

plugin 9:
    id: com.github.hierynomus.license-report
    version: 0.15.0
    implementationClass: com.hierynomus.gradle.license.LicenseReportingPlugin

plugin 10:
    id: com.github.hierynomus.license-base
    version: 0.15.0
    implementationClass: com.hierynomus.gradle.license.LicenseBasePlugin

plugin 11:
    id: com.github.hierynomus.license
    version: 0.15.0
    implementationClass: nl.javadude.gradle.plugins.license.LicensePlugin

plugin 12:
    id: org.kordamp.gradle.licensing
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.licensing.LicensingPlugin
    enabled: false

plugin 13:
    id: jacoco
    version: {gradle-version}
    implementationClass: org.gradle.testing.jacoco.plugins.JacocoPlugin

plugin 14:
    id: org.kordamp.gradle.jacoco
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.jacoco.JacocoPlugin
    enabled: true

plugin 15:
    id: com.github.kt3k.coveralls
    version: 2.10.2
    implementationClass: org.kt3k.gradle.plugin.CoverallsPlugin

plugin 16:
    id: org.kordamp.gradle.coveralls
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.coveralls.CoverallsPlugin
    enabled: true

plugin 17:
    id: org.kordamp.gradle.publishing
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.publishing.PublishingPlugin
    enabled: true

plugin 18:
    id: signing
    version: {gradle-version}
    implementationClass: org.gradle.plugins.signing.SigningPlugin

plugin 19:
    id: org.kordamp.gradle.minpom
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.minpom.MinPomPlugin
    enabled: true

plugin 20:
    id: org.kordamp.gradle.jar
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.jar.JarPlugin
    enabled: true

plugin 21:
    id: org.kordamp.gradle.source-jar
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.source.SourceJarPlugin
    enabled: true

plugin 22:
    id: org.kordamp.gradle.source-stats
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.stats.SourceStatsPlugin
    enabled: true

plugin 23:
    id: org.kordamp.gradle.source-html
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.sourcehtml.SourceHtmlPlugin
    enabled: true

plugin 24:
    id: org.kordamp.gradle.source-xref
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.sourcexref.SourceXrefPlugin
    enabled: true

plugin 25:
    id: org.kordamp.gradle.bintray
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.bintray.BintrayPlugin
    enabled: true

plugin 26:
    id: org.kordamp.gradle.testing
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.testing.TestingPlugin
    enabled: true

plugin 27:
    id: com.github.ben-manes.versions
    version: 0.33.0
    implementationClass: com.github.benmanes.gradle.versions.VersionsPlugin

plugin 28:
    id: org.kordamp.gradle.project
    version: {project-version}
    implementationClass: org.kordamp.gradle.plugin.project.ProjectPlugin
    enabled: true

plugin 29:
    id: net.nemerosa.versioning
    version: 2.14.0
    implementationClass: net.nemerosa.versioning.VersioningPlugin
----

[[_task_properties]]
=== ProjectProperties

Displays all properties found in a project

[horizontal]
Name:: projectProperties
Type:: `org.kordamp.gradle.plugin.base.tasks.PropertiesTask`

.Options
[horizontal]
section:: The section to generate the report for.
show-secrets:: Show secret values instead of masked values. Value masking is applied to properties that contain any
of the following words: `secret`, `password`, `credential`, `token`, `apikey`. The list of words can be overriden by
setting a System property named `kordamp.secret.keywords` to a comma delimited String, such as `password,secret`.

Valid values for `section` are: project, ext.

==== Example Output

For a project defined as follows

[source,java]
.~/.gradle/gradle.properties
----
global_property = global
----

[source,java]
.gradle.properties
----
version        = 0.0.0
group          = org.kordamp.sample.acme
local_property = local
----

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

ext.build_property = 'build'

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

Invoking these command

[source]
----
$ gm :projectProperties -Pproject_property=project
----

Results in the following output

[source]
----
> Task :projectProperties
project:
    name: sample
    version: 0.0.0
    group: org.kordamp.sample.acme
    path: :
    displayName: root project 'sample'
    projectDir: /tmp/sample
    buildFile: /tmp/sample/build.gradle
    buildDir: /tmp/sample/build

ext:
    build_property: build
    global_property: global
    local_property: local
    project_property: project
----

[[_task_repositories]]
=== Repositories

Displays all repositories used for resolving project dependencies

[horizontal]
Name:: repositories
Type:: `org.kordamp.gradle.plugin.base.tasks.RepositoriesTask`

==== Example Output

For a project defined as follows

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}

repositories {
    jcenter()
    mavenCentral()
    flatDir { dirs 'lib' }
}
----

Invoking these command

[source]
----
$ gm :repositories
----

Results in the following output

[source]
----
> Task :repositories
Total repositories: 3

repository 0:
    type: maven
    name: BintrayJCenter
    url: https://jcenter.bintray.com/

repository 1:
    type: maven
    name: MavenRepo
    url: https://repo.maven.apache.org/maven2/

repository 2:
    type: flatDir
    name: flatDir
    dirs:
        /tmp/sample/lib
----

[[_task_tar_settings]]
=== TarSettings

Display TAR settings.

[horizontal]
Name:: tarSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.TarSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
task:: The task to generate the report for.
tasks:: The tasks to generate the report for.

You may specify either of the two, be advised that `tasks` has precedence over `task`. All tasks will be displayed
if neither of these options is specified.

[[_task_task_settings]]
=== TaskSettings

Display settings of a Task

[horizontal]
Name:: taskSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.TaskSettingsTask`

.Options
[horizontal]
task:: The task to generate the report for.

[[_task_verify]]
=== Verify

Assembles and tests the project. This is an alias for `build`.

[horizontal]
Name:: verify
Type:: `org.gradle.api.DefaultTask`

[[_task_zip_settings]]
=== ZipSettings

Display ZIP settings.

[horizontal]
Name:: zipSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.ZipSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
task:: The task to generate the report for.
tasks:: The tasks to generate the report for.

You may specify either of the two, be advised that `tasks` has precedence over `task`. All tasks will be displayed
if neither of these options is specified.

[[_org_kordamp_gradle_base_rules]]
== Rules

=== Configurations

[horizontal]
Pattern:: <ConfigurationName>ConfigurationSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.ConfigurationSettingsTask`

=== Extensions

[horizontal]
Pattern:: <ExtensionName>ExtensionSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.ExtensionSettingsTask`

=== Tars

[horizontal]
Pattern:: <TarName>TarSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.TarSettingsTask`

=== Tasks

[horizontal]
Pattern:: <TaskName>TaskSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.TaskSettingsTask`

=== Zips

[horizontal]
Pattern:: <ZipName>ZipSettings
Type:: `org.kordamp.gradle.plugin.base.tasks.ZipSettingsTask`
