
[[_org_kordamp_gradle_bom]]
= Bom

[horizontal]
id:: `org.kordamp.gradle.bom`
class:: `org.kordamp.gradle.plugin.bom.BomPlugin`
    (link:api/org/kordamp/gradle/plugin/bom/BomPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/bom/BomPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`, +
`link:https://docs.gradle.org/current/userguide/bom_maven.html[maven-publish]`, +
`link:https://docs.gradle.org/current/userguide/signing_plugin.html[signing]`

Configures a MavenPublication for the project using the core `maven-publish` plugin.
The name of the publication matches `"main"`.

Data defined in the DSL's `config.info` and `config.license` blocks will be used to fill out information required by the
generated BOM file. Artifacts will be automatically signed if the `uploadArchives` task is present.

[[_org_kordamp_gradle_bom_example]]
== Example

Using the following project layout as an example

[source,groovy]
----
.
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradle.properties
├── gradlew
├── gradlew.bat
├── settings.gradle
├── docs
│   └── guide
│       ├── guide.gradle
│       └── src
│           └── docs
│               ├── asciidoc
│               └── resources
└── subprojects
    ├── sample-bom
    │   └── sample-bom.gradle
    ├── project1
    │   ├── project1.gradle
    │   └── src
    │       └── main
    └── project2
        ├── project2.gradle
        └── src
            └── main
----

With the following content set in the `sample-bom.gradle` build file

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.sample-bom.gradle (child)
----
apply plugin: 'org.kordamp.gradle.bom'

config {
    bom {
        exclude('guide')
    }
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.sample-bom.gradle.kts (child)
----
apply(plugin = "org.kordamp.gradle.bom")

config {
    bom {
        exclude("guide")
    }
}
----

Results in the following BOM when invoking `gradle :sample-bom:publish`

[source,xml,subs="verbatim"]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.kordamp.sample.acme</groupId>
  <artifactId>sample-bom</artifactId>
  <version>0.0.0</version>
  <packaging>pom</packaging>
  <name>Sample</name>
  <description>sample-bom</description>
  <url>https://github.com/joecool/sample</url>
  <inceptionYear>2018</inceptionYear>
  <licenses>
    <license>
      <name>Apache-2.0</name>
      <url>https://spdx.org/licenses/Apache-2.0.html</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>joecool</id>
      <name>Joe Cool</name>
      <roles>
        <role>developer</role>
      </roles>
    </developer>
  </developers>
  <scm>
    <url>https://github.com/joecool/sample.git</url>
  </scm>
  <properties>
    <sample.version>0.0.0</sample.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.kordamp.sample.acme</groupId>
        <artifactId>project1</artifactId>
        <version>${sample.version}</version>
      </dependency>
      <dependency>
        <groupId>org.kordamp.sample.acme</groupId>
        <artifactId>project2</artifactId>
        <version>${sample.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
----

[[_org_kordamp_gradle_bom_dsl]]
== DSL

[source,groovy]
----
config {
    bom {
        autoIncludes
        enabled
        dependencies
        excludes
        includes
        properties
        parent
        overwriteInceptionYear
        overwriteUrl
        overwriteLicenses
        overwriteScm
        overwriteOrganization
        overwriteDevelopers
        overwriteContributors
    }
}
----

[options="header", cols="5*"]
|===
| Name                   | Type                    | Required | Default Value | Description
| enabled                | boolean                 | no       | true          | Disables `org.kordamp.gradle.bom` plugin if `false`
| autoIncludes           | boolean                 | no       | true          | Disables default inclusion of all projects
| dependencies           | Map<String, Dependency> | no       | [:]           | Dependencies that should be added to the BOM
| excludes               | Set<String>             | no       | []            | Names of subprojects that should not be included
| includes               | Set<String>             | no       | []            | Names of subprojects that should be included
| properties             | Map<String, String>     | no       | [:]           | Maps to `<properties>` block.
| parent                 | String                  | no       |               | Defines the coordinates of the parent POM
| overwriteInceptionYear | boolean                 | no       | false         | Overwrite `<inceptionYear>` from parent POM
| overwriteUrl           | boolean                 | no       | false         | Overwrite `<url>` from parent POM
| overwriteLicenses      | boolean                 | no       | false         | Overwrite `<licenses>` from parent POM
| overwriteScm           | boolean                 | no       | false         | Overwrite `<scm>` from parent POM
| overwriteOrganization  | boolean                 | no       | false         | Overwrite `<organization>` from parent POM
| overwriteDevelopers    | boolean                 | no       | false         | Overwrite `<developers>` from parent POM
| overwriteContributors  | boolean                 | no       | false         | Overwrite `<contributors>` from parent POM
|===

The format for `parent` may be any of the following ones:

 * Plain name of a project within the same multi-project, i.e. `kordamp-core`.
 * Project path within the same multi-project, i.e. `:kordamp-core`.
 * Full maven coordinates, i.e. `org.kordamp:kordamp-core:1.2.3`.

This block is optional.

[[_org_kordamp_gradle_bom_dsl_methods]]
=== Methods

exclude(String):: Skips the named project from being added to the BOM.
include(String):: Adds the named project to the BOM.
dependency(String gavNotation):: Defines a dependency. Argument must use the `groupId:artifactId:version` notation. Dependency name will be equal to `artifactId`. +
Example: +
[source,groovy]
----
dependency('com.googlecode.guava:guava:29.0-jre')
----
dependency(String name, String gavNotation):: Defines a dependency. Second argument must use the `groupId:artifactId:version` notation. +
Example: +
[source,groovy]
----
dependency('guava', 'com.googlecode.guava:guava:29.0-jre')
----
dependency(String name, String gavNotation, Action action):: Defines and configures a dependency. Second argument must use the `groupId:artifactId:version` notation. +
Example: +
[source,groovy]
----
dependency('groovy', 'org.codehaus.groovy:groovy:3.0.6') {
    modules = [
        'groovy-test',
        'groovy-json',
        'groovy-xml'
    ]
}
----
dependency(String name, String gavNotation, Closure action):: Defines and configures a dependency. Second argument must use the `groupId:artifactId:version` notation. +
Example: +
[source,groovy]
----
dependency('groovy', 'org.codehaus.groovy:groovy:3.0.6') {
    modules = [
        'groovy-test',
        'groovy-json',
        'groovy-xml'
    ]
}
----
platform(String gavNotation):: Defines a platform dependency. Argument must use the `groupId:artifactId:version` notation. Dependency name will be equal to `artifactId`. +
Example: +
[source,groovy]
----
platform('io.micronaut:micronaut-bom:2.0.2')
----
platform(String name, String gavNotation):: Defines a platform dependency. Second argument must use the `groupId:artifactId:version` notation. +
Example: +
[source,groovy]
----
platform('micronaut', 'io.micronaut:micronaut-bom:2.0.2')
----
dependency(String gavNotation, Action action):: Defines and configures a dependency by name. +
Example: +
[source,groovy]
----
dependency('org.codehaus.groovy:groovy:3.0.6') {
    modules = [
        'groovy-test',
        'groovy-json',
        'groovy-xml'
    ]
}
----
dependency(String gavNotation, Closure action):: Defines and configures a dependency by name. +
Example: +
[source,groovy]
----
dependency('org.codehaus.groovy:groovy:3.0.6') {
    modules = [
        'groovy-test',
        'groovy-json',
        'groovy-xml'
    ]
}
----
getDependency(String name):: Returns the named dependency (if it exists). Throws an exception otherwise. +
The `name` parameter may be the logical name or the `groupId:artifactId` of the dependency. +
Example: +
[source,groovy]
----
getDependency('guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
getDependency('com.googlecode.guava:guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
----
findDependency(String nameOrGa):: Finds a dependency by name or GA if it exists, `null` otherwise. +
Example: +
[source,groovy]
----
findDependency('guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
findDependency('com.googlecode.guava:guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
----
findDependencyByName(String name):: Finds a dependency by name if it exists, `null` otherwise. +
Example: +
[source,groovy]
----
findDependencyByName('guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
----
findDependencyByGA(String name, String moduleNAme):: Finds a dependency by groupId and artifactId if it exists, `null` otherwise. +
Example: +
[source,groovy]
----
findDependencyByGA('com.googlecode.guava', 'guava') instanceof org.kordamp.gradle.plugin.base.model.artifact.Dependency
----
getPlatform(String name):: Returns the named platform (if it exists). Throws an exception otherwise. +
The `name` parameter may be the logical name or the `groupId:artifactId` of the platform. +
Example: +
[source,groovy]
----
getPlatform('micronaut') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
getPlatform('io.micronaut:micronaut-bom') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
----
findPlatform(String nameOrGa):: Returns the named platform (if it exists).
The `nameOrGa` parameter may be the logical name or the `groupId:artifactId` of the platform. +
Example: +
[source,groovy]
----
findPlatform('micronaut') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
findPlatform('io.micronaut:micronaut-bom') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
----
findPlatformByName(String name):: Finds a platform by name if it exists, `null` otherwise. +
Example: +
[source,groovy]
----
findPlatformByName('micronaut') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
----
findPlatformByGA(String name, String moduleNAme):: Finds a platform by groupId and artifactId if it exists, `null` otherwise. +
Example: +
[source,groovy]
----
findPlatformByGA('io.micronaut', 'micronaut-bom') instanceof org.kordamp.gradle.plugin.base.model.artifact.Platform
----
gav(String name):: Returns the given dependency in GAV notation if it exists. Throws an exception otherwise. +
The `name` parameter may be the logical name or the `groupId:artifactId` of the dependency. +
Example: +
[source,groovy]
----
gav('groovy') == 'org.codehaus.groovy:groovy:3.0.6'
gav('org.codehaus.groovy:groovy') == 'org.codehaus.groovy:groovy:3.0.6'
----
gav(String name, String moduleName):: Returns the given module dependency in GAV notation if it exists. Throws an exception otherwise. +
The `name` parameter may be the logical name or the `groupId:artifactId` of the dependency. +
Example: +
[source,groovy]
----
gav('groovy', 'groovy-json') == 'org.codehaus.groovy:groovy-json:3.0.6'
gav('org.codehaus.groovy:groovy', 'groovy-json') == 'org.codehaus.groovy:groovy-json:3.0.6'
----
ga(String name, String moduleName):: Returns the given module dependency in GA (groupId/artifactId) notation if it exists. Throws an exception otherwise. +
The `name` parameter may be the logical name or the `groupId:artifactId` of the dependency. +
Example: +
[source,groovy]
----
ga('micronaut', 'micronaut-core') == 'io.micronaut:micronaut-core'
ga('io.micronaut:micronaut-bom', 'micronaut-core') == 'io.micronaut:micronaut-core'
----

WARNING: Instances of type `org.kordamp.gradle.plugin.base.model.artifact.Dependency` or `org.kordamp.gradle.plugin.base.model.artifact.Platform`
can not be passed directly to Gradle's dependency resolution mechanism. You must convert them to any of the accepted
notations such as `groupId:artifactId:version`, use the `gav()` or `ga()` utility methods instead.

