
[[_org_kordamp_gradle_codenarc]]
= Codenarc

[horizontal]
id:: `org.kordamp.gradle.codenarc`
class:: `org.kordamp.gradle.plugin.codenarc.CodenarcPlugin`
    (link:api/org/kordamp/gradle/plugin/codenarc/CodenarcPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/codenarc/CodenarcPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`, +
`link:https://docs.gradle.org/current/userguide/codenarc_plugin.html[codenarc]`

Configures Codenarc on Groovy projects and aggregate reports on the root project.

[[_org_kordamp_gradle_codenarc_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    quality {
        codenarc {
            enabled
            configFile
            maxPriority1Violations
            maxPriority2Violations
            maxPriority3Violations
            toolVersion
            <<_codenarc_aggregate,aggregate>> {
                enabled
                excludedProjects
            }
        }
    }
}
----

[options="header", cols="5*"]
|===
| Name                   | Type        | Required | Default Value | Description
| enabled                | boolean     | no       | true          | Disables `org.kordamp.gradle.codenarc` plugin if `false`
| configFile             | Set<String> | no       |               |
| maxPriority1Violations | int         | no       |               |
| maxPriority2Violations | int         | no       |               |
| maxPriority3Violations | int         | no       |               |
| toolVersion            | String      | no       | 1.5           |
| excludedSourceSets     | Set<String> | no       | []            |
|===

The value of `configFile` will be automatically calculated based on the following rules

* Explicit value if set in the build file, with ${sourceSetName} as suffix.
* Explicit value if set in the build file.
* `config/codenarc/${project.name}-${sourceSetName}.groovy`
* `config/codenarc/${project.name}.groovy`
* `config/codenarc/codenarc-${sourceSetName}.groovy`
* `config/codenarc/codenarc.groovy`
* `config/codenarc/${project.name}-${sourceSetName}.xml`
* `config/codenarc/${project.name}.xml`
* `config/codenarc/codenarc-${sourceSetName}.xml`
* `config/codenarc/codenarc.xml`

.Methods

void excludeSourceSet(String):: Adds a sourceSet exclusion.

[[_codenarc_aggregate]]
*aggregate*

[options="header", cols="5*"]
|===
| Name             | Type         | Required | Default Value | Description
| enabled          | boolean      | no       | true          | Enables or disables aggregation
| excludedProjects | Set<Project> |          | []            | Projects in the set are excluded from aggregation
|===

This block should be configured on the root project.

[[_org_kordamp_gradle_codenarc_tasks]]
== Tasks

[[_task_aggregate_codenarc]]
=== AggregateCodenarc

Aggregates all codenarc reports for all projects. +
Consumes settings from `config.quality.<<_org_kordamp_gradle_codenarc_dsl,codenarc>>`. +
This task is added to the root project.

[horizontal]
Name:: aggregateCodenarc
Type:: `org.gradle.api.plugins.quality.CodeNarc`

.Properties
[horizontal]
reports.html.destination:: `${project.buildDir}/reports/codenarc/aggregate.html`
reports.xml.destination:: `${project.buildDir}/reports/codenarc/aggregate.xml`

[[_task_all_codenarc]]
=== AllCodenarc

Aggregates all codenarc reports for a single project. +
Consumes settings from `config.quality.<<_org_kordamp_gradle_codenarc_dsl,codenarc>>`.

[horizontal]
Name:: allCodenarc
Type:: `org.gradle.api.plugins.quality.CodeNarc`

.Properties
[horizontal]
reports.html.destination:: `${project.buildDir}/reports/codenarc/${project.name}.html`
reports.xml.destination:: `${project.buildDir}/reports/codenarc/${project.name}.xml`

[[_task_init_codenarc]]
=== InitCodenarc

Creates a default Codenarc configuration file.

[horizontal]
Name:: initCodenarc
Type:: `org.kordamp.gradle.plugin.codenarc.tasks.InitCodenarcTask`

.Properties
[horizontal]
destinationDir:: `${rootProject.projectDir}/config/codenarc`
overwrite:: Overwrite existing file if there's a match

