
[[_org_kordamp_gradle_groovydoc]]
= Groovydoc

[horizontal]
id:: `org.kordamp.gradle.groovydoc`
class:: `org.kordamp.gradle.plugin.groovydoc.GroovydocPlugin`
    (link:api/org/kordamp/gradle/plugin/groovydoc/GroovydocPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/groovydoc/GroovydocPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`, +
`link:https://docs.gradle.org/current/userguide/groovy_plugin.html[groovy]`
applied by:: `<<_org_kordamp_gradle_groovy_project,org.kordamp.gradle.groovy-project>>`

Generates and packages Groovydoc documentation.

[[_org_kordamp_gradle_groovydoc_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    docs {
        groovydoc {
            enabled
            empty
            includes
            excludes
            replaceJavadoc
            <<_groovydoc_options,options>> {
                windowTitle
                docTitle
                header
                footer
                overviewText
                links
                noTimestamp
                noVersionStamp
                includePrivate
                use
            }
            <<_groovydoc_aggregate,aggregate>> {
                enabled
                empty
                fast
                replaceJavadoc
                excludedProjects
            }
        }
    }
}
----

[options="header", cols="5*"]
|===
| Name           | Type        | Required | Default Value | Description
| enabled        | boolean     | no       | true          | Disables `org.kordamp.gradle.groovydoc` plugin if `false`
| empty          | boolean     | no       | false         | Generates an empty JAR if `true`.
| includes       | Set<String> | no       | []            |
| excludes       | Set<String> | no       | []            |
| replaceJavadoc | boolean     | no       | false         | Disables `javadocJar` and applies the `javadoc` classifier
|===

.Methods

void exclude(String):: Adds a source exclusion rule (Ant pattern).
void include(String):: Adds a source inclusion rule (Ant pattern).

[[_groovydoc_options]]
*options*

[options="header", cols="5*"]
|===
| Name           | Type         | Required | Default Value                        | Description
| windowTitle    | String       | no       | "${project.name} ${project.version}" |
| docTitle       | String       | no       | "${project.name} ${project.version}" |
| header         | String       | no       | "${project.name} ${project.version}" |
| footer         | String       | no       |                                      |
| overviewText   | TextResource | no       |                                      |
| links          | Set<Link>    | no       |                                      | The default value contains links to the target Java and latest Groovy javadocs.
| noTimestamp    | boolean      | no       |                                      |
| noVersionStamp | boolean      | no       |                                      |
| includePrivate | boolean      | no       | true                                 |
| use            | boolean      | no       | true                                 |
|===

This block is optional.

[[_groovydoc_aggregate]]
*aggregate*

[options="header", cols="5*"]
|===
| Name             | Type         | Required | Default Value | Description
| enabled          | boolean      | no       | true          | Enables or disables aggregation
| empty            | boolean      | no       | false         | Generates an empty JAR if `true`.
| fast             | boolean      | no       | true          | Does not execute child `groovydoc` tasks if `true`
| replaceJavadoc   | boolean      | no       | false         | Disables `aggregateJavadoc` and applies the `javadoc` classifier
| excludedProjects | Set<Project> |          | []            | Projects in the set are excluded from aggregation
|===

This block should be configured on the root project.

[[_org_kordamp_gradle_groovydoc_tasks]]
== Tasks

[[_task_aggregate_groovydoc]]
=== AggregateGroovydoc

Aggregates Groovy API docs for all projects. +
Consumes settings from `config.<<_org_kordamp_gradle_groovydoc,groovydoc>>` defined in the root project. +
This task is added to the root project.

[horizontal]
Name:: aggregateGroovydoc
Type:: `org.gradle.api.tasks.javadoc.Groovydoc`

.Properties
[horizontal]
destinationDir:: `${rootProject.buildDir}/docs/aggregate-groovydoc`

[[_task_aggregate_groovydoc_jar]]
=== AggregateGroovydocJar

An archive of the aggregate Groovy API docs. +
This task is added to the root project.

[horizontal]
Name:: aggregateGroovydocJar
Type:: `org.gradle.api.tasks.bundling.Jar`

.Properties
[horizontal]
classifier:: groovydoc
destinationDir:: `${rootProject.buildDir}/build/libs`

[[_task_groovydoc]]
=== Groovydoc

Generates Groovydoc API documentation. +
Consumes settings from `config.<<_org_kordamp_gradle_groovydoc_dsl,groovydoc>>`.

[horizontal]
Name:: groovydoc
Type:: `org.gradle.api.tasks.javadoc.Groovydoc`

.Properties
[horizontal]
destinationDir:: `${project.buildDir}/docs/groovydoc`

[[_task_groovydoc_jar]]
=== GroovydocJar

An archive of the Groovydoc API docs.

[horizontal]
Name:: groovydocJar
Type:: `org.gradle.api.tasks.bundling.Jar`

.Properties
[horizontal]
classifier:: groovydoc | javadoc
destinationDir:: `${project.buildDir}/build/libs`
from:: `groovydoc.destinationDir`

