
[[_org_kordamp_gradle_inline]]
= Inline

[horizontal]
id:: `org.kordamp.gradle.inline`
class:: `org.kordamp.gradle.plugin.inline.InlinePlugin`
    (link:api/org/kordamp/gradle/plugin/inline/InlinePlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/inline/InlinePlugin.html[source])

NOTE: This plugin should be applied to `settings.gradle(.kts)` only!

Enables invocation of any Gradle plugin by providing GAV coordinates plus a given task name. Core Gradle plugins are also
supported in which case you only have to specify their plugin id, not their GAV coordinates.

The `inline` plugin chooses the target `Project` on which plugins will be applied based on the following rules:

 * If the `inline.target` System property is set:
 ** All projects if the value is `all`.
 ** All projects except root if value is `subprojects`.
 ** Project(s) whose path matches the value (exactly or as regex). Value may be command separated.
 * The project whose `projectDir` matches the start parameter `-p` or `--project-dir` when given.
 * The project whose `buildFile` matches the start parameter `-b` or `--build-file` when given.
 * The project whose `projectDir` matches the current directory.
 * The root project.

Plugin properties, such as those exposed by extensions added by plugins, may be adapted so that their values may
be supplied using System and/or project properties. These are the default property adapters provided by the `org.kordamp.gradle.inline`
plugin:

link:api/org/kordamp/gradle/plugin/inline/adapters/ApplicationPluginPropertyAdapter.html[ApplicationPluginPropertyAdapter]
Adapts the `link:https://docs.gradle.org/current/userguide/application_plugin.html[application]` plugin. Supported properties are:

 * application.mainClass - requires Gradle 6.4+
 * application.mainModule - requires Gradle 6.4+
 * application.mainClassName
 * application.applicationDefaultJvmArgs

Custom property adapters may be added to the classpath. Such adapters must implement
link:api/org/kordamp/gradle/plugin/inline/PropertyAdapter.html[PropertyAdapter] and be registered as a service in
`META-INF/services/org.kordamp.gradle.plugin.inline.PropertyAdapter`.

This plugin also lets you invoke tasks prefixed by a project path regex, in which case all projects whose paths match
the given regex will be affected by the given goal.

[[_org_kordamp_gradle_inline_example]]
== Example

Invoking the `<<_org_kordamp_gradle_echo,echo>>` plugin

[source,subs="attributes"]
----
$ gm {project-group}:echo-gradle-plugin:{project-version}:echo -Decho.message="Hello World"
----

Invoking the `application` plugin

[source,subs="attributes"]
----
$ gm application:run -Dapplication.mainClass=com.acme.Main
----

Invoking the `distZip` goal on all projects that have `-app` in their paths

[source,subs="attributes"]
----
$ gm :*-app:distZip
----

