
[[_org_kordamp_gradle_inline]]
= Inline

[horizontal]
id:: `org.kordamp.gradle.inline`
class:: `org.kordamp.gradle.plugin.inline.InlinePlugin`
    (link:api/org/kordamp/gradle/plugin/inline/InlinePlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/inline/InlinePlugin.html[source])

NOTE: This plugin should be applied to `settings.gradle(.kts)` only!

Enables invocation of any Gradle plugin by providing GAV coordinates plus a given task name. Core Gradle plugins are also
supported in which case you only have to specify their plugin id, not their GAV coordinates.

The following formats for including plugins are supported:

 1. `pluginId:task` where `pluginId` is either a core Gradle plugin or an aliased plugin.
 2. `pluginId:version:task` where `pluginId` is a core Gradle plugin or an aliased plugin.
 3. `groupId:artifactId:version:task`.
 4. `groupId:artifactId:task` where `version` will be set as `latest.release`.

Aliased plugins require an additional resource that identifies their `groupId` and `artifactId` coordinates. This resource
may be placed inside `$HOME/.gradle/org.kordamp.gradle.inline/` as a properties file. The name of the file identifies the
`groupId`. Every key in the file defines a `pluginId` while the value is the matching `artifactId`.

The following example shows how the link:https://github.com/jbangdev/jbang-gradle-plugin[jbang-gradle-plugin] may be configured
to take advantage of this feature

.$HOME/.gradle/org.kordamp.gradle.inline/dev.jbang.properties
[source,java]
----
dev.jbang=jbang-gradle-plugin
----

Additionaly this plugin will also search the classpath for resources at `META-INF/org.kordamp.gradle.inline` that follow
the same rules as above. Given that order matters it's possible to define sorting order for all resolved groupIds by defining
a value for the `org.kordamp.gradle.inline.plugin.groups` System property, which is a comma separated list of groupIds.

The `inline` plugin chooses the target `Project` on which plugins will be applied based on the following rules:

 * If the `inline.target` System property is set:
 ** All projects if the value is `all`.
 ** All projects except root if value is `subprojects`.
 ** Project(s) whose path matches the value (exactly or as regex). Value may be command separated.
 * The project whose `projectDir` matches the start parameter `-p` or `--project-dir` when given.
 * The project whose `buildFile` matches the start parameter `-b` or `--build-file` when given.
 * The project whose `projectDir` matches the current directory.
 * The root project.

Plugin properties, such as those exposed by extensions added by plugins, may be adapted so that their values may
be supplied using System and/or project properties. These are the default property adapters provided by the `org.kordamp.gradle.inline`
plugin:

link:api/org/kordamp/gradle/plugin/inline/adapters/ApplicationPluginPropertyAdapter.html[ApplicationPluginPropertyAdapter]::
Adapts the `link:https://docs.gradle.org/current/userguide/application_plugin.html[application]` plugin. Supported properties are:

 * `application.mainClass` - requires Gradle 6.4+; aliased to `exec.mainClass`.
 * `application.mainModule` - requires Gradle 6.4+
 * `application.mainClassName` - aliased to `exec.mainClass`.
 * `application.applicationDefaultJvmArgs` - aliased to `exec.args`.

Custom property adapters may be added to the classpath. Such adapters must implement
link:api/org/kordamp/gradle/plugin/inline/PropertyAdapter.html[PropertyAdapter] and be registered as a service in
`META-INF/services/org.kordamp.gradle.plugin.inline.PropertyAdapter`.

This plugin also lets you invoke tasks prefixed by a project path regex, in which case all projects whose paths match
the given regex will be affected by the given goal.

[[_org_kordamp_gradle_inline_properties]]
== Flags

The following flags may be set using System properties to alter the behavior of this plugin

org.kordamp.gradle.inline.enabled::
Disable all capabilities of this plugin if set to `false`. Default is `true`.
org.kordamp.gradle.inline.project.regex::
Disable evaluation of project regexes if set to `false`. Default is `true`.
org.kordamp.gradle.inline.plugins::
Disable inlining plugins if set to `false`. Default is `true`.
org.kordamp.gradle.inline.adapt::
Disable adapting task properties with link:api/org/kordamp/gradle/plugin/inline/PropertyAdapter.html[PropertyAdapter] instances
if set to `false`. Default is `true`.
org.kordamp.gradle.inline.plugin.groups::
List of groupIds to be queried in order for resolving pluginId aliases.

[[_org_kordamp_gradle_inline_example]]
== Example

Invoking the `<<_org_kordamp_gradle_echo,echo>>` plugin

[source,subs="attributes"]
----
$ gm {project-group}:echo-gradle-plugin:{project-version}:echo -Decho.message="Hello World"
----

Invoking the latest release of the `<<_org_kordamp_gradle_echo,echo>>` plugin

[source,subs="attributes"]
----
$ gm {project-group}:echo-gradle-plugin:echo -Decho.message="Hello World"
----

Invoking a given release of the `<<_org_kordamp_gradle_echo,echo>>` plugin using an alias

[source,subs="attributes"]
----
$ gm {project-group}.echo:{project-version}:echo -Decho.message="Hello World"
----

Invoking the latest release of the `<<_org_kordamp_gradle_echo,echo>>` plugin using an alias

[source,subs="attributes"]
----
$ gm {project-group}.echo:echo -Decho.message="Hello World"
----

Invoking the `application` plugin

[source,subs="attributes"]
----
$ gm application:run -Dapplication.mainClass=com.acme.Main
----

Invoking the `distZip` goal on all projects that have `-app` in their paths

[source,subs="attributes"]
----
$ gm :*-app:distZip
----

[[_org_kordamp_gradle_inline_aliases]]
== Plugin Aliases

The following are the aliases for all Kordamp plugins, some of which are not included in this plugin suite

.META-INF/org.kordamp.gradle.inline/org.kordamp.gradle.properties
[source,java,subs="attributes"]
----
include::{rootdir}/plugins/inline-gradle-plugin/src/main/resources/META-INF/org.kordamp.gradle.inline/org.kordamp.gradle.properties[lines=19..-1]
----

