
[[_org_kordamp_gradle_integrationtest]]
= IntegrationTest

[horizontal]
id:: `org.kordamp.gradle.integration-test`
class:: `org.kordamp.gradle.plugin.integrationtest.IntegrationTestPlugin`
    (link:api/org/kordamp/gradle/plugin/integrationtest/IntegrationTestPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/integrationtest/IntegrationTestPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`

Responsibilities:

 * Create two additional configurations: `integrationTestImplementation` and `integrationTestRuntimeOnly`. These configurations
   extend from `testImplementation` and `testRuntimeOnly` respectively.
 * Create a `SourceSet` named `integrationTest` pointing to `${config.testing.integration.baseDir}/[java|groovy|kotlin|scala]`.
 * Create a `Test` task named `integrationTest` pointing to `${config.testing.integration.baseDir}/[java|groovy|kotlin|scala]`.
 * Create a `TestReport` task named `integrationTestReport`. This task is added as a dependency to `check`.

