
[[_org_kordamp_gradle_jacoco]]
= JaCoCo

[horizontal]
id:: `org.kordamp.gradle.jacoco`
class:: `org.kordamp.gradle.plugin.jacoco.JacocoPlugin`
    (link:api/org/kordamp/gradle/plugin/jacoco/JacocoPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/jacoco/JacocoPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`, +
`link:https://docs.gradle.org/current/userguide/jacoco_plugin.html[jacoco]`
applied by:: `<<_org_kordamp_gradle_project,org.kordamp.gradle.project>>`

Configures JaCoCo on all subprojects that contains tests. +
Configures aggregate reports on the root project.

[[_org_kordamp_gradle_jacoco_dsl]]
== DSL

[source,groovy]
----
config {
    coverage {
        jacoco {
            enabled
            aggregateExecFile
            aggregateReportHtmlFile
            aggregateReportXmlFile
            additionalSourceDirs
            additionalClassDirs
            toolVersion
            excludes
            includeProjectDependencies
        }
    }
}
----

[options="header", cols="5*"]
|===
| Name                       | Type           | Required | Default Value                                                     | Description
| enabled                    | boolean        | no       | true                                                              | Disables `org.kordamp.gradle.jacoco` plugin if `false`
| aggregateExecFile          | File           | no       | ${project.buildDir}/jacoco/aggregate.exec                         | Location for the aggregate merge execution data file
| aggregateReportHtmlFile    | File           | no       | ${project.buildDir}/reports/jacoco/aggregate/html                 | Location for aggregate HTML reports
| aggregateReportXmlFile     | File           | no       | ${project.buildDir}/reports/jacoco/aggregate/jacocoTestReport.xml | Location for the aggregate XML report
| additionalSourceDirs       | FileCollection | no       | []                                                                | Additional source directories
| additionalClassDirs        | FileCollection | no       | []                                                                | Additional class directories
| toolVersion                | String         | no       | {jacocoVersion}                                                   |
| excludes                   | Set<String>    | no       | []                                                                |
| includeProjectDependencies | boolean        | no       | false                                                             |
|===

The value for `enabled` will automatically be set to `false` if no tests (`unit`, `integration`, or `functional`) are found.

If `includeProjectDependencies` is set to `true` then class files from all projects that have been set as dependencies will
also be included  in the generated report. This setting applies for individual projects and is ignored on aggregate root
reports as all project sources are already taken into account.

This block is optional.

.Methods

void exclude(String):: Adds a source exclusion rule (Ant pattern).

[[_org_kordamp_gradle_jacoco_tasks]]
== Tasks

[[_task_aggregate_jacoco_merge]]
=== AggregateJacocoMerge

Aggregates all execution data into a single file. +
Consumes settings from `config.<<_org_kordamp_gradle_jacoco_dsl,jacoco>>` defined in the root project. +
This task is added to the root project.

[horizontal]
Name:: aggregateJacocoMerge
Type:: `org.gradle.testing.jacoco.tasks.JacocoMerge`

.Properties
[horizontal]
destinationFile:: config.docs.jacoco.aggregateExecFile

[[_task_aggregate_jacoco_report]]
=== AggregateJacocoReport

Aggregates all coverage reports into a single report. +
Consumes settings from `config.<<_org_kordamp_gradle_jacoco_dsl,jacoco>>` defined in the root project. +
This task is added to the root project.

[horizontal]
Name:: aggregateJacocoReport
Type:: `org.gradle.testing.jacoco.tasks.JacocoReport`

.Properties
[horizontal]
reports.html.destination:: config.docs.jacoco.aggregateReportHtmlFile
reports.xml.destination:: config..jacoco.aggregateReportXmlFile
reports.html.enabled:: true
reports.xml.enabled:: true

[[_task_all_jacoco_reports]]
=== AllJacocoReports

Executes all JaCoCo reports found in a project (unit, integration, functional, etc).

[horizontal]
Name:: allTests
Type:: `org.gradle.api.DefaultTask`

[[_task_jacoco_report]]
=== Jacoco<Test>Report

Generates code coverage report for a task of type `link:https://docs.gradle.org/4.10/dsl/org.gradle.api.tasks.testing.Test.html[Test]`. +

[horizontal]
Name:: jacoco<Name>Report, where `Name` stands for the name of the matching `Test` task.
Type:: `org.gradle.testing.jacoco.tasks.JacocoReport`

.Properties
[horizontal]
additionalSourceDirs:: jacoco.additionalSourceDirs
sourceDirectories:: jacoco.additionalSourceDirs
classDirectories:: jacoco.additionalClassDirs
executionData:: testTask
reports.html.destination:: "${project.reporting.baseDir.path}/jacoco/${testTask.name}/html"
reports.xml.destination:: "${project.reporting.baseDir.path}/jacoco/${testTask.name}/jacocoTestReport.xml"
reports.csv.enabled:: false
reports.html.enabled:: true
reports.xml.enabled:: true
