
[[_org_kordamp_gradle_java_project]]
= JavaProject

[horizontal]
id:: `org.kordamp.gradle.java-project`
class:: `org.kordamp.gradle.plugin.project.java.JavaProjectPlugin`
    (link:api/org/kordamp/gradle/plugin/project/java/JavaProjectPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/project/java/JavaProjectPlugin.html[source])
applies:: `<<_org_kordamp_gradle_project,org.kordamp.gradle.project>>`
applied by:: `<<_org_kordamp_gradle_groovy_project,org.kordamp.gradle.groovy-project>>`

Configures a project with Java conventions.

This plugin adds the following plugins to the classpath without applying them:

 * `<<_org_kordamp_gradle_checkstyle,org.kordamp.gradle.checkstyle>>`
 * `<<_org_kordamp_gradle_pmd,org.kordamp.gradle.pmd>>`
 * `<<_org_kordamp_gradle_errorprone,org.kordamp.gradle.errorprone>>`
 * `<<_org_kordamp_gradle_spotbugs,org.kordamp.gradle.spotbugs>>`

[[_org_kordamp_gradle_java_project_configurations]]
== Configurations

[[_org_kordamp_gradle_java_project_configuration_optional]]
=== Optional

A configuration that behaves like Maven's `<optional>` flag. Dependencies added to this configuration will be available to
`compileClasspath` and `runtimeClasspath` but won't be exported in the generated POM.

[[_org_kordamp_gradle_java_project_extensions]]
== Extensions

[[_org_kordamp_gradle_java_project_extension_applyToDefaults]]
=== applyToDefaults

Configures platform dependencies based on settings available from `config.dependencyManagement`. Since Gradle 6 platform dependencies
must be applied per configuration, which results in verbose build files when a  BOM/platform should be applied in common
configurations. This extension lets you apply a BOM/platform to multiple configurations with a single method call.
The following configurations will be used:

* `api`
* `implementation`
* `annotationProcessor`
* `testImplementation`
* `testAnnotationProcessor`
* `compileOnly`
* `testCompileOnly`
* `runtimeOnly`
* `testRuntimeOnly`

[horizontal]
Name:: applyToDefaults
Type:: `org.kordamp.gradle.plugin.project.DefaultConfigurationsDependencyHandler`
Applied to:: `org.gradle.api.artifacts.dsl.DependencyHandler`

.Methods

void platform(Object notation):: Declares a dependency on a platform.
void platform(Object notation, Action<? super Dependency> action):: Declares and configures a dependency on a platform.
void enforcedPlatform(Object notation):: Declares a dependency on an enforced platform.
void enforcedPlatform(Object notation, Action<? super Dependency> action):: Declares and configures a dependency on an enforced platform.

Where `notation` may be one of

* `java.lang.CharSequence` with format `groupId:artifactId:version`.
* `java.util.Map` with `group`, `artifactId`, `version` keys.
* `java.lang.CharSequence` with the name of a platform declared in `config.dependencyManagement`.

.Example
The following example shows how the Micronaut BOM can be used to configure all configurations

[source,groovy]
.build.gradle
----
config {
    dependencyManagement {
        platform('micronaut', "io.micronaut:micronaut-bom:$micronautVersion")
    }
}

dependencies {
    applyToDefaults.enforcedPlatform('micronaut')

    // The following dependencies can now be resolved by their respective configurations
    // without specifying a version as the 'micronaut' platform will provide it
    annotationProcessor('io.micronaut:micronaut-inject-java')
    annotationProcessor('io.micronaut:micronaut-validation')
    api('io.micronaut:micronaut-validation')
    compileOnly('io.micronaut:micronaut-inject-groovy')
}
----

[[_org_kordamp_gradle_java_project_extension_applyTo]]
=== applyTo

Configures platform, module, and regular dependencies based on settings available from `config.dependencyManagement`.

[horizontal]
Name:: applyTo
Type:: `org.kordamp.gradle.plugin.project.ConfigurationsDependencyHandler`
Applied to:: `org.gradle.api.artifacts.dsl.DependencyHandler`

.Methods

DependencyHandlerSpec configuration(String configuration)::
Declares the target configuration on which platforms and dependencies will be applied
DependencyHandlerSpec configurations(String configuration, String... configurations)::
Declares target configurations on which platforms and dependencies will be applied.
DependencyHandlerSpec configurations(Set<String> configurations)::
Declares target configurations on which platforms and dependencies will be applied.
DependencyHandlerSpec c(String configuration)::
Declares the target configuration on which platforms and dependencies will be applied. +
Alias for `configuration(configuration)`.
DependencyHandlerSpec c(String configuration, String... configurations)::
Declares target configurations on which platforms and dependencies will be applied. +
Alias for `configurations(configuration,configurations)`.
DependencyHandlerSpec c(Set<String> configurations)::
Declares target configurations on which platforms and dependencies will be applied. +
Alias for `configurations(configurations)`.

`DependencyHandlerSpec` has the following methods

void platform(Object notation):: Declares a dependency on a platform.
void platform(Object notation, Action<? super Dependency> action):: Declares and configures a dependency on a platform.
void enforcedPlatform(Object notation):: Declares a dependency on an enforced platform.
void enforcedPlatform(Object notation, Action<? super Dependency> action):: Declares and configures a dependency on an enforced platform.
void dependency(String nameOrGav):: Declares a dependency.
void dependency(String nameOrGav, Closure):: Declares and configures a dependency.
void module(String nameOrGa):: Declares a module dependency (from a platform).
void module(String nameOrGa, Closure):: Declares and configures a module dependency (from a platform).

Where `notation` may be one of

* `java.lang.CharSequence` with format `groupId:artifactId:version`.
* `java.util.Map` with `group`, `artifactId`, `version` keys.
* `java.lang.CharSequence` with the name of a platform declared in `config.dependencyManagement`.

.Example
The following example shows how the Micronaut BOM can be used to configure all configurations

[source,groovy]
.build.gradle
----
config {
    dependencyManagement {
        dependency('junit:junit:4.13')
        platform('micronaut', "io.micronaut:micronaut-bom:$micronautVersion")
    }
}

dependencies {
    applyToDefaults.enforcedPlatform('micronaut')

    // The following dependencies can now be resolved by their respective configurations
    // without specifying a version as the 'micronaut' platform will provide it

    applyTo.configuration('annotationProcessor').module('micronaut', 'micronaut-inject-java')
    // apply to both annotationProcessor & api
    applyTo.c('annotationProcessor', 'api').module('micronaut', 'micronaut-validation')
    applyTo.c('api').module('micronaut', 'micronaut-runtime-groovy')
    applyTo.c('testImplementation').dependency('junit')
    // undeclared dependencies require the use of groupId:artifactId:version
    applyTo.c('testImplementation').dependency('org.hamcrest:hamcrest-core:2.2')
}
----

[[_org_kordamp_gradle_java_project_tasks]]
== Tasks

[[_task_compile]]
=== Compile

Assembles main classes. This is an alias for `classes`.

[horizontal]
Name:: classes
Type:: `org.gradle.api.DefaultTask`

[[_task_jar_settings]]
=== JarSettings

Display JAR settings.

[horizontal]
Name:: jarSettings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.JarSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
task:: The task to generate the report for.
tasks:: The tasks to generate the report for.

You may specify either of the two, be advised that `tasks` has precedence over `task`. All tasks will be displayed
if neither of these options is specified.

[[_task_java_compiler_settings]]
=== JavaCompilerSettings

Display Java compiler settings.

[horizontal]
Name:: javaCompilerSettings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.JavaCompilerSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
task:: The task to generate the report for.
tasks:: The tasks to generate the report for.

You may specify either of the two, be advised that `tasks` has precedence over `task`. All tasks will be displayed
if neither of these options is specified.

[[_task_platforms]]
=== Platforms

Displays all configured platforms in the project. Requires the use of the <<_org_kordamp_gradle_java_project_extension_applyTo,applyTo>> or
<<_org_kordamp_gradle_java_project_extension_applyToDefaults,applyToDefaults>> extensions.

[horizontal]
Name:: platforms
Type:: `org.kordamp.gradle.plugin.project.java.tasks.platformsTask`

==== Example Output

For a project with the following dependencies

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
dependencies {
    applyToDefaults.enforcedPlatform("io.micronaut:micronaut-bom:$micronautVersion")

    annotationProcessor 'io.micronaut:micronaut-inject-java'
    annotationProcessor 'io.micronaut:micronaut-validation'

    compileOnly 'io.micronaut:micronaut-inject-groovy'

    api 'io.micronaut:micronaut-inject'
    api 'io.micronaut:micronaut-validation'
    api 'io.micronaut:micronaut-runtime-groovy'
}
----

Invoking this command

[source]
----
$ gm :platforms
----

Results in the following output

[source]
----
> Task :platforms
Total platforms: 1

Platform 0:
    platform: io.micronaut:micronaut-bom:2.0.2
    enforced: true
    configurations:
        api
        implementation
        annotationProcessor
        testImplementation
        testAnnotationProcessor
        compileOnly
        testCompileOnly
        runtimeOnly
        testRuntimeOnly
----

[[_task_sourceSets]]
=== SourceSets

Displays all sourceSets available in a project.

[horizontal]
Name:: sourceSets
Type:: `org.kordamp.gradle.plugin.project.java.tasks.SourceSetsTask`

==== Example Output

For a project defined as follows

[source,groovy,subs="verbatim,attributes"]
.build.gradle
----
plugins {
    id 'java-library'
    id 'org.kordamp.gradle.project' version '{project-version}'
}

config {
    licensing  { enabled = false }

    publishing { enabled = false }
}
----

Invoking this command

[source]
----
$ gm :sourceSets
----

Results in the following output

[source]
----
> Task :sourceSets
Total sourceSets: 2

sourceSet 0:
    name: main

sourceSet 1:
    name: test
----

[[_task_source_set_settings]]
=== SourceSetSettings

Display settings of a SourceSet

[horizontal]
Name:: sourceSetSettings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.SourceSetSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
sourceSet:: The sourceSet to generate the report for.
sourceSets:: The sourceSets to generate the report for.

You may specify either of the two, be advised that `sourceSets` has precedence over `sourceSet`. All sourceSets will be displayed
if neither of these options is specified.

[[_task_test_settings]]
=== TestSettings

Display test task settings.

[horizontal]
Name:: testSettings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.TestSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
task:: The task to generate the report for.
tasks:: The tasks to generate the report for.

You may specify either of the two, be advised that `tasks` has precedence over `task`. All tasks will be displayed
if neither of these options is specified.

[[_task_war_settings]]
=== WarSettings

Display WAR settings.

[horizontal]
Name:: warSettings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.WarSettingsTask`

.Options
[horizontal]
show-paths:: Display path information (OPTIONAL).
task:: The task to generate the report for.
tasks:: The tasks to generate the report for.

You may specify either of the two, be advised that `tasks` has precedence over `task`. All tasks will be displayed
if neither of these options is specified.

[[_org_kordamp_gradle_java_project_rules]]
== Rules

=== CompileJava

[horizontal]
Pattern:: compile<SourceSetName>JavaSettings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.JavaCompilerSettingsTask`

=== Jars

[horizontal]
Pattern:: <JarName>JarSettings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.JarSettingsTask`

=== JavaExec

[horizontal]
Pattern:: <TaskName>Settings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.JavaExecSettingsTask`

=== SourceSets

[horizontal]
Pattern:: <SourceSetName>SourceSetSettings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.SourceSetSettingsTask`

=== Tests

[horizontal]
Pattern:: <SourceSetName>TestSettings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.TestSettingsTask`

=== Wars

[horizontal]
Pattern:: <WarName>JarSettings
Type:: `org.kordamp.gradle.plugin.project.java.tasks.WarSettingsTask`
