
[[_org_kordamp_gradle_plugins]]
= Plugins

[horizontal]
id:: `org.kordamp.gradle.plugin`
class:: `org.kordamp.gradle.plugin.plugin.PluginPlugin`
    (link:api/org/kordamp/gradle/plugin/plugin/PluginPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/plugin/PluginPlugin.html[source])
applies::  `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>` +
`link:https://docs.gradle.org/current/userguide/java_gradle_plugin.html#java_gradle_plugin[java-gradle-plugin]` +
`link:https://plugins.gradle.org/docs/publish-plugin[com.gradle.publish-plugin]`

Configures a Gradle plugin project with `java-gradle-plugin` and `publish-plugin` using data defined
in the `<<_org_kordamp_gradle_base,info>>` block of the `config` DSL. Artifacts will be automatically signed if the
`uploadArchives` task is present.

NOTE: This plugin must be explicitly applied to Gradle plugin projects only.

[[_org_kordamp_gradle_plugin_dsl]]
== DSL

[source,groovy]
----
config {
    plugins {
        enabled
        plugin {
            id
            name
            description
            displayName
            implementationClass
            tags
        }
    }
}
----

[options="header", cols="5*"]
|===
| Name    | Type    | Required | Default Value | Description
| enabled | boolean | no       | true          | Disables `org.kordamp.gradle.plugin` plugin if `false`
|===

[[_plugins_plugin]]
*plugin*

|===
| Name                | Type         | Required | Default Value | Description
| id                  | String       | yes      |               | Defines the plugin's id
| name                | String       | yes      |               | Defines the plugin's name
| description         | String       | no       |               | Defines the plugin's description
| displayName         | String       | no       |               | Defines the plugin's display name
| implementationClass | String       | yes      |               | Defines the plugin's implementation Class
| tags                | List<String> | no       | []            |
|===

This block defines a single plugin entry. You may define as many plugins as needed.

[[_org_kordamp_gradle_plugins_tasks]]
== Tasks

[[_task_list_plugins_descriptors]]
=== ListPluginDescriptors

Lists plugin descriptors from plugin declarations.

[horizontal]
Name:: listPluginDescriptors
Type:: `org.kordamp.gradle.plugin.plugin.ListPluginDescriptorsTask`


