
[[_org_kordamp_gradle_project]]
= Project

[horizontal]
id:: `org.kordamp.gradle.project`
class:: `org.kordamp.gradle.plugin.project.ProjectPlugin`
    (link:api/org/kordamp/gradle/plugin/project/ProjectPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/project/ProjectPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`, +
`<<_org_kordamp_gradle_profiles,org.kordamp.gradle.profiles>>`, +
`<<_org_kordamp_gradle_buildinfo,org.kordamp.gradle.build-info>>`, +
`<<_org_kordamp_gradle_jacoco,org.kordamp.gradle.jacoco>>`, +
`<<_org_kordamp_gradle_coveralls,org.kordamp.gradle.coveralls>>`, +
`<<_org_kordamp_gradle_jar,org.kordamp.gradle.jar>>`, +
`<<_org_kordamp_gradle_javadoc,org.kordamp.gradle.javadoc>>`, +
`<<_org_kordamp_gradle_licensing,org.kordamp.gradle.licensing>>`, +
`<<_org_kordamp_gradle_minpom,org.kordamp.gradle.minpom>>`, +
`<<_org_kordamp_gradle_publishing,org.kordamp.gradle.publishing>>`, +
`<<_org_kordamp_gradle_source,org.kordamp.gradle.source-jar>>`, +
`<<_org_kordamp_gradle_sourcehtml,org.kordamp.gradle.source-html>>`, +
`<<_org_kordamp_gradle_sourcestats,org.kordamp.gradle.source-stats>>`, +
`<<_org_kordamp_gradle_testing,org.kordamp.gradle.testing>>`, +
`https://github.com/ben-manes/gradle-versions-plugin[com.github.ben-manes.versions]`
applied by:: `<<_org_kordamp_gradle_java_project,org.kordamp.gradle.java-project>>`

Serves as central point of configuration for a project as it applies all dependent plugins. You may skip this plugin
and apply plugins individually as needed.

This plugin adds the following plugins to the classpath without applying them:

 * `<<_org_kordamp_gradle_bintray,org.kordamp.gradle.bintray>>`
 * `<<_org_kordamp_gradle_bom,org.kordamp.gradle.bom>>`
 * `<<_org_kordamp_gradle_clirr,org.kordamp.gradle.clirr>>`
 * `<<_org_kordamp_gradle_sourcexref,org.kordamp.gradle.source-xref>>`
 * `<<_org_kordamp_gradle_integrationtest,org.kordamp.gradle.integration-test>>`
 * `<<_org_kordamp_gradle_functionaltest,org.kordamp.gradle.functional-test>>`

[[_org_kordamp_gradle_project_tasks]]
== Tasks

[[_task_copy_dependencies]]
=== CopyDependencies

Copies dependencies for a given configuration.

[horizontal]
Name:: copyDependencies
Type:: `org.kordamp.gradle.plugin.project.tasks.CopyDependenciesTask`

.Options
[horizontal]
configuration:: The name of the configuration (REQUIRED).
layout:: The layout type (OPTIONAL). Valid values are [`flat`, `default`].
includes:: Comma separated artifact patterns, e.g, `<groupId>:<artifactId>:<version>:<classifier>`
excludes:: Comma separated artifact patterns, e.g, `<groupId>:<artifactId>:<version>:<classifier>`

.Properties
[horizontal]
configuration:: The name of the configuration (REQUIRED).
layout:: The layout type (OPTIONAL). Valid values are [`flat`, `default`].
outputDirectory:: The target directory where artifacts will be written to. Defaults to `${buildDir}/dependencies/${layout}`.
includes:: Artifact patterns, e.g, `<groupId>:<artifactId>:<version>:<classifier>`
excludes:: Artifact patterns, e.g, `<groupId>:<artifactId>:<version>:<classifier>`

.Artifact pattern examples:

* org.apache.maven
* org.apache.maven:badArtifact
* org.apache.maven:artifact:badVersion
* org.apache.maven:*:1.2 (exclude version 1.2 and above, equivalent to [1.2,) )
* org.apache.maven:*:[1.2] (explicit exclude of version 1.2)
* org.apache.maven:*:*:test
* org.apache.+*+:maven-+*+:*

