
[[_org_kordamp_gradle_publishing]]
= Publishing

[horizontal]
id:: `org.kordamp.gradle.publishing`
class:: `org.kordamp.gradle.plugin.publishing.PublishingPlugin`
    (link:api/org/kordamp/gradle/plugin/publishing/PublishingPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/publishing/PublishingPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`, +
`<<_org_kordamp_gradle_buildinfo,org.kordamp.gradle.build-info>>`, +
`<<_org_kordamp_gradle_jar,org.kordamp.gradle.jar>>`, +
`<<_org_kordamp_gradle_minpom,org.kordamp.gradle.minpom>>`, +
`<<_org_kordamp_gradle_source,org.kordamp.gradle.source-jar>>` +
`link:https://docs.gradle.org/current/userguide/publishing_maven.html[maven-publish]`, +
`link:https://docs.gradle.org/current/userguide/signing_plugin.html[signing]`

Configures a MavenPublication for the project's artifacts using the core `maven-publish` plugin.
The name of the publication matches `"main"`. Published artifacts include the main JAR, sources,
javadoc/groovydoc/kotlindoc/scaladoc JARs.  Artifacts will be automatically signed if the `uploadArchives` task is present.

Data defined in the DSL's `config.info` and `config.licensing` blocks will be used to fill out information required by the
generated POM file.

[[_org_kordamp_gradle_publishing_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    publishing {
        enabled
        signing
        releasesRepository
        snapshotsRepository
        publications
        scopes
        flattenPlatforms
        useVersionExpressions
        <<_publishing_pom,pom>>  {
            properties
            parent
            overwriteInceptionYear
            overwriteUrl
            overwriteLicenses
            overwriteScm
            overwriteOrganization
            overwriteDevelopers
            overwriteContributors
        }
    }
}
----

[options="header", cols="5*"]
|===
| Name                  | Type         | Required | Default Value | Description
| enabled               | boolean      | no       | true          | Disables `org.kordamp.gradle.publishing` plugin if `false`
| signing               | boolean      | no       | false         | Enables signing of all artifacts associated with `main`
| releasesRepository    | String       | no       |               | Name of a Maven compatible repository for publishing releases
| snapshotsRepository   | String       | no       |               | Name of a Maven compatible repository for publishing snapshots
| publications          | List<String> | no       | []            | Publication names to be included
| scopes                | List<String> | no       | []            | Maven scopes to be added to generated POM. If no value then defaults to `['compile', 'runtime']`
| flattenPlatforms      | boolean      | no       | false         | Expand dependencies imported from platforms and skip adding platforms to `<dependencyManagement>`
| useVersionExpressions | boolean      | no       | true          | Substitute dependency version numbers with version expressions added to `<properties>`
|===

This block is optional.

[[_publishing_pom]]
*pom*

[options="header", cols="5*"]
|===
| Name                   | Type                | Required | Default Value | Description
| packaging              | String              | no       | jar           | Defines the value for `<packaging>`
| properties             | Map<String, String> | no       | [:]           | Maps to `<properties>` block.
| parent                 | String              | no       |               | Defines the coordinates of the parent POM
| overwriteInceptionYear | boolean             | no       | false         | Overwrite `<inceptionYear>` from parent POM
| overwriteUrl           | boolean             | no       | false         | Overwrite `<url>` from parent POM
| overwriteLicenses      | boolean             | no       | false         | Overwrite `<licenses>` from parent POM
| overwriteScm           | boolean             | no       | false         | Overwrite `<scm>` from parent POM
| overwriteOrganization  | boolean             | no       | false         | Overwrite `<organization>` from parent POM
| overwriteDevelopers    | boolean             | no       | false         | Overwrite `<developers>` from parent POM
| overwriteContributors  | boolean             | no       | false         | Overwrite `<contributors>` from parent POM
|===

The format for `parent` may be any of the following ones:

 * Plain name of a project within the same multi-project, i.e. `kordamp-core`.
 * Project path within the same multi-project, i.e. `:kordamp-core`.
 * Full maven coordinates, i.e. `org.kordamp:kordamp-core:1.2.3`.

This block is optional.

[[_org_kordamp_gradle_publishing_example]]
== Example

Publishing signed artifacts to Maven Central.

[source,groovy]
.build.gradle
----
config {
    info {
        repositories {
            repository {
                name = 'mavenRelease'
                url  = 'https://oss.sonatype.org/service/local/staging/deploy/maven2/'
                credentials {
                    username = ...
                    password = ...
                }
            }
            repository {
                name = 'mavenSnapshot'
                url  = 'https://oss.sonatype.org/content/repositories/snapshots/'
                credentials {
                    username = ...
                    password = ...
                }
            }
        }
    }

    publishing {
        signing = true
        releasesRepository  = 'mavenRelease'
        snapshotsRepository = 'mavenSnapshot'
    }
}
----

[[_org_kordamp_gradle_publishing_tasks]]
== Tasks

[[_task_publication_settings]]
=== PublicationSettings

Display publication configuration

[horizontal]
Name:: publicationSettings
Type:: `org.kordamp.gradle.plugin.publishing.PublicationSettingsTask`

.Options
[horizontal]
absolute:: Should paths be printed as absolutes or not. Defaults to 'false' (OPTIONAL).
publication:: The publication to generate the report for.
publications:: The publications to generate the report for.

You may specify either of the two, be advised that `publications` has precedence over `publication`. All publications will be displayed
if neither of these options is specified.

[[_org_kordamp_gradle_publishing_rules]]
== Rules

=== Publications

[horizontal]
Pattern:: <PublicationName>PublicationSettings
Type:: `org.kordamp.gradle.plugin.publishing.PublicationSettingsTask`
