
[[_org_kordamp_gradle_publishing]]
= Publishing

[horizontal]
id:: `org.kordamp.gradle.publishing`
class:: `org.kordamp.gradle.plugin.publishing.PublishingPlugin`
    (link:api/org/kordamp/gradle/plugin/publishing/PublishingPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/publishing/PublishingPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`, +
`<<_org_kordamp_gradle_buildinfo,org.kordamp.gradle.build-info>>`, +
`<<_org_kordamp_gradle_jar,org.kordamp.gradle.jar>>`, +
`<<_org_kordamp_gradle_minpom,org.kordamp.gradle.minpom>>`, +
`<<_org_kordamp_gradle_source,org.kordamp.gradle.source-jar>>` +
`link:https://docs.gradle.org/current/userguide/publishing_maven.html[maven-publish]`, +
`link:https://docs.gradle.org/current/userguide/signing_plugin.html[signing]`
applied by:: `<<_org_kordamp_gradle_project,org.kordamp.gradle.project>>`

Configures a MavenPublication for the project's artifacts using the core `maven-publish` plugin.
The name of the publication matches `"main"`. Published artifacts include the main JAR, sources,
javadoc/groovydoc JARs.

Data defined in the DSL's `config.info` and `config.licensing` blocks will be used to fill out information required by the
generated POM file.

[[_org_kordamp_gradle_publishing_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    publishing {
        enabled
        releasesRepository
        snapshotsRepository
        publications
        scopes
        flattenPlatforms
        useVersionExpressions
        <<_publishing_signing,signing>> {
            enabled
            keyId
            secretKey
            password
        }
        <<_publishing_maven_central,mavenCentral>> {
            enabled
            username
            password
            publishingType
            timeoutSeconds
        }
        <<_publishing_pom,pom>>  {
            properties
            parent
            overwriteInceptionYear
            overwriteUrl
            overwriteLicenses
            overwriteScm
            overwriteOrganization
            overwriteDevelopers
            overwriteContributors
        }
    }
}
----

[options="header", cols="5*"]
|===
| Name                  | Type         | Required | Default Value | Description
| enabled               | boolean      | no       | true          | Disables `org.kordamp.gradle.publishing` plugin if `false`
| releasesRepository    | String       | no       |               | Name of a Maven compatible repository for publishing releases
| snapshotsRepository   | String       | no       |               | Name of a Maven compatible repository for publishing snapshots
| publications          | List<String> | no       | []            | Publication names to be included
| scopes                | List<String> | no       | []            | Maven scopes to be added to generated POM. If no value then defaults to `['compile', 'runtime']`
| flattenPlatforms      | boolean      | no       | false         | Expand dependencies imported from platforms and skip adding platforms to `<dependencyManagement>`
| useVersionExpressions | boolean      | no       | true          | Substitute dependency version numbers with version expressions added to `<properties>`
|===

This block is optional.

[[_publishing_signing]]
*signing*

[options="header", cols="5*"]
|===
| Name      | Type    | Required | Default Value | Description
| enabled   | boolean | no       | false         | Disables artifact signing if `false`
| keyId     | String  | no       |               | The public key ID (The last 8 symbols of the keyId. You can use `gpg -K` to get it)
| secretKey | String  | no       |               | Ascii armored secret key used for signing
| password  | String  | no       |               | The passphrase used to protect the private key
|===

If `signing` is set to `true` and no other properties are set then the signatory is expected to be set by conventional
means explained at link:https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signatory_credentials[Signatory credentials].

If both `secretKey` and `password` are set then the signatory will use an
link:https://docs.gradle.org/current/userguide/signing_plugin.html#sec:in-memory-keys[in-memory ascii-armored key].

If `keyId`, `secretKey`, and `password` are set then the signatory will use an
link:https://docs.gradle.org/current/userguide/signing_plugin.html#using_in_memory_ascii_armored_openpgp_subkeys[in-memory ascii-armored OpenPGP subkey].

[[_publishing_maven_central]]
*mavenCentral*

[options="header", cols="5*"]
|===
| Name           | Type    | Required | Default Value | Description
| enabled        | boolean | no       | false         | Enables Maven Central publishing using the new REST API
| username       | String  | no       |               | Maven Central username (user token)
| password       | String  | no       |               | Maven Central password (user token)
| publishingType | String  | no       | USER_MANAGED  | Publishing type: `AUTOMATIC` or `USER_MANAGED`
| timeoutSeconds | int     | no       | 300           | HTTP timeout in seconds for API calls
|===

Maven Central publishing uses the new link:https://central.sonatype.org/publish/publish-portal-api/[Central Publisher Portal API] introduced in 2024.
This replaces the legacy OSSRH workflow with a modern REST API approach.

When `mavenCentral.enabled` is set to `true`, the plugin will:

1. Create ZIP bundles containing all required artifacts (JAR, sources, javadoc, POM, signatures)
2. Upload bundles to Maven Central using the REST API
3. Handle validation and publishing workflow
4. Support both automatic and user-managed publishing modes

*Publishing Types:*

- `AUTOMATIC`: Deployments are automatically published after successful validation
- `USER_MANAGED`: Deployments require manual approval via the Central Portal UI or API

*Authentication:*

The `username` and `password` should be your Maven Central user token credentials, not your Sonatype account credentials.
These can be obtained from your link:https://central.sonatype.com/[Central Portal] account settings.

[[_publishing_pom]]
*pom*

[options="header", cols="5*"]
|===
| Name                   | Type                | Required | Default Value | Description
| packaging              | String              | no       | jar           | Defines the value for `<packaging>`
| properties             | Map<String, String> | no       | [:]           | Maps to `<properties>` block.
| parent                 | String              | no       |               | Defines the coordinates of the parent POM
| overwriteInceptionYear | boolean             | no       | false         | Overwrite `<inceptionYear>` from parent POM
| overwriteUrl           | boolean             | no       | false         | Overwrite `<url>` from parent POM
| overwriteLicenses      | boolean             | no       | false         | Overwrite `<licenses>` from parent POM
| overwriteScm           | boolean             | no       | false         | Overwrite `<scm>` from parent POM
| overwriteOrganization  | boolean             | no       | false         | Overwrite `<organization>` from parent POM
| overwriteDevelopers    | boolean             | no       | false         | Overwrite `<developers>` from parent POM
| overwriteContributors  | boolean             | no       | false         | Overwrite `<contributors>` from parent POM
|===

The format for `parent` may be any of the following ones:

 * Plain name of a project within the same multi-project, i.e. `kordamp-core`.
 * Project path within the same multi-project, i.e. `:kordamp-core`.
 * Full maven coordinates, i.e. `org.kordamp:kordamp-core:1.2.3`.

This block is optional.

[[_org_kordamp_gradle_publishing_example]]
== Examples

=== Legacy OSSRH Publishing

Publishing signed artifacts to Maven Central using the legacy OSSRH workflow.

[source,groovy]
.build.gradle
----
config {
    info {
        repositories {
            repository {
                name = 'mavenRelease'
                url  = 'https://oss.sonatype.org/service/local/staging/deploy/maven2/'
                credentials {
                    username = ...
                    password = ...
                }
            }
            repository {
                name = 'mavenSnapshot'
                url  = 'https://oss.sonatype.org/content/repositories/snapshots/'
                credentials {
                    username = ...
                    password = ...
                }
            }
        }
    }

    publishing {
        signing {
            enabled = true
        }
        releasesRepository  = 'mavenRelease'
        snapshotsRepository = 'mavenSnapshot'
    }
}
----

=== Maven Central REST API Publishing

Publishing signed artifacts to Maven Central using the new REST API (recommended).

[source,groovy]
.build.gradle
----
config {
    publishing {
        signing {
            enabled = true
            keyId = System.getenv('SIGNING_KEY_ID')
            secretKey = System.getenv('SIGNING_SECRET_KEY')
            password = System.getenv('SIGNING_PASSWORD')
        }
        
        mavenCentral {
            enabled = true
            username = System.getenv('MAVEN_CENTRAL_USERNAME')
            password = System.getenv('MAVEN_CENTRAL_PASSWORD')
            publishingType = 'AUTOMATIC'
            timeoutSeconds = 600
        }
    }
}
----

*Environment Variables:*

[source,bash]
----
export SIGNING_KEY_ID="12345678"
export SIGNING_SECRET_KEY="-----BEGIN PGP PRIVATE KEY BLOCK-----..."
export SIGNING_PASSWORD="your-key-password"
export MAVEN_CENTRAL_USERNAME="your-user-token"
export MAVEN_CENTRAL_PASSWORD="your-user-token-password"
----

*Publishing Commands:*

[source,bash]
----
# Publish to Maven Central
./gradlew publishToMavenCentral

# Drop a failed deployment
./gradlew dropMavenCentralDeployment --deployment-id=abc123

# Enable automatic publishing for a deployment
./gradlew enableAutomaticMavenCentralPublishing --deployment-id=abc123
----

[[_org_kordamp_gradle_publishing_tasks]]
== Tasks

[[_task_publication_settings]]
=== PublicationSettings

Display publication configuration

[horizontal]
Name:: publicationSettings
Type:: `org.kordamp.gradle.plugin.publishing.PublicationSettingsTask`

.Options
[horizontal]
absolute:: Should paths be printed as absolutes or not. Defaults to 'false' (OPTIONAL).
publication:: The publication to generate the report for.
publications:: The publications to generate the report for.

You may specify either of the two, be advised that `publications` has precedence over `publication`. All publications will be displayed
if neither of these options is specified.

[[_task_prepare_maven_central_publishing]]
=== PrepareMavenCentralPublishing

Prepares Maven Central publishing by registering the project with the Maven Central build service.

[horizontal]
Name:: prepareMavenCentralPublishing
Type:: `org.kordamp.gradle.plugin.publishing.central.PrepareMavenCentralPublishingTask`

[[_task_publish_to_maven_central]]
=== PublishToMavenCentral

Publishes artifacts to Maven Central using the new REST API.

[horizontal]
Name:: publishToMavenCentral
Type:: `org.kordamp.gradle.plugin.publishing.central.PublishToMavenCentralTask`

This task depends on `prepareMavenCentralPublishing` and all Maven publication tasks.

[[_task_drop_maven_central_deployment]]
=== DropMavenCentralDeployment

Drops a Maven Central deployment.

[horizontal]
Name:: dropMavenCentralDeployment
Type:: `org.kordamp.gradle.plugin.publishing.central.DropMavenCentralDeploymentTask`

.Options
[horizontal]
deployment-id:: The deployment ID to drop (REQUIRED).

[[_task_enable_automatic_maven_central_publishing]]
=== EnableAutomaticMavenCentralPublishing

Enables automatic publishing for a Maven Central deployment.

[horizontal]
Name:: enableAutomaticMavenCentralPublishing
Type:: `org.kordamp.gradle.plugin.publishing.central.EnableAutomaticMavenCentralPublishingTask`

.Options
[horizontal]
deployment-id:: The deployment ID to enable automatic publishing for (REQUIRED).

[[_org_kordamp_gradle_publishing_rules]]
== Rules

=== Publications

[horizontal]
Pattern:: <PublicationName>PublicationSettings
Type:: `org.kordamp.gradle.plugin.publishing.PublicationSettingsTask`
