
[[_org_kordamp_gradle_settings]]
= Settings

[horizontal]
id:: `org.kordamp.gradle.settings`
class:: `org.kordamp.gradle.plugin.settings.SettingsPlugin`
    (link:api/org/kordamp/gradle/plugin/settings/SettingsPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/settings/SettingsPlugin.html[source])

NOTE: This plugin should be applied to `settings.gradle(.kts)` only!

Configures the root project by automatically including subprojects. The root project must abide
to one of the following layouts:

two-level::
Subprojects are defined using a two-level directory structure, typically grouped by responsibility,
for example

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
├── docs
│   └── guide
│       └── guide.gradle
└── subprojects
    ├── project1
    │   ├── project1.gradle
    └── project2
        └── project2.gradle
----

multi-level::
Subprojects are defined using any directory structure, for example

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
├── guide
│   └── guide.gradle
└── subprojects
    ├── project1
    │   ├── project1.gradle
    └── project2
        └── project2.gradle
----

standard::
Suprojects are defined as direct children of the root project, for example

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
├── guide
│   └── guide.gradle
├── project1
│   └── project1.gradle
└── project2
    └── project2.gradle
----

Build files should be renamed to match their containing directory unless `enforceNamingConvention` is set
to `false`, in which case the default build file name (`build.gradle`, `build.gradle.kts`) applies.

[[_org_kordamp_gradle_settings_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
projects {
    cache
    layout
    enforceNamingConvention
    directories
    excludes
    fileNameTransformation
    prefix
    suffix

    includeProjects(String dir)
        .exclude(String projectName)  // optional
        .when(boolean)                // optional
    includeProjects(String dir)
        .exclude(String projectName)  // optional
        .when(Supplier<Boolean>)      // optional

    includeProject(String projectFilePath)
         .when(boolean)               // optional
    includeProject(String projectFilePath)
        .when(Supplier<Boolean>)      // optional

    <<_plugins_dsl,plugins>> { }
}
----

[options="header", cols="5*"]
|===
| Name                    | Type                   | Required | Default Value | Description
| cache                   | boolean                | no       | false         | If `true` then the project structure will be cached.
| layout                  | Layout                 | no       | TWO_LEVEL     | Defines the project layout. Valid values are [TWO_LEVEL, MULTI_LEVEL, STANDARD, EXPLICIT]. +
                                                                                Also accepts literal values [`two-level`, `multi-level`, `standard`, `explicit`].
| enforceNamingConvention | boolean                | no       | true          | If `true` then build file names must match their containing project directory name.
| useLongPaths            | boolean                | no       | false         | If `true` then projects will use their long paths when layout != `standard`.
| directories             | List<String>           | no*      | []            | List of directories to include for `two-level` and `multi-level` layout.
| excludes                | List<String>           | no       | []            | List of directories to be excluded from automatic inclusion.
| fileNameTransformation  | FileNameTransformation | no       |               | Transformation applied to build file name. Valid values are [ADD, REMOVE]. +
                                                                                Also accepts literal values [`add`, `remove`].
| prefix                  | String                 | no       |               | Prefix added/removed from build file name.
| suffix                  | String                 | no       |               | Suffix added/removed from build file name.
|===

The `directories` property is not required if the chosen layout is set to `standard` or `explicit`. It may be omitted if the chosen layout
is `two-level` however is recommended to define it if the search space is too big (too many first level directories).

The use of this DSL implies the computation of the root project's structure on every build. You can cache the project structure
by settings `cache` to `true`. The cache will be automatically invalidated if the settings file is updated in any way, thus
when adding or removing a project directory for autodiscovery you must, at least, modify the last modified timestamp of the
settings file, typically by invoking the `touch` OS command on the file, failing that make a simple edit and save the file.

[[_org_kordamp_gradle_settings_methods]]
=== Methods

The following methods should be used when the chosen layout is `explicit`, otherwise no additional projects will be discovered
and included in the build

*includeProjects(String dir)* +
Includes projects found under the given directory unless the given condition (`when()`) evaluates to false.

*exclude(String)* +
Excludes a project directory by name.

*includeProject(String path)* +
Includes a project found under the given path unless the given condition (`when()`) evaluates to false.

[[_org_kordamp_gradle_settings_example]]
== Example

.Two-Level

A project with the following structure

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
├── docs
│   └── guide
│       └── guide.gradle
└── subprojects
    ├── project1
    │   ├── project1.gradle
    └── project2
        └── project2.gradle
----

Can be configured as follows

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.settings.gradle
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.kordamp.gradle:settings-gradle-plugin:{project-version}'
    }
}
apply plugin: 'org.kordamp.gradle.settings'

projects {
    directories = ['docs', 'subprojects']
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.settings.gradle.kts
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("org.kordamp.gradle:settings-gradle-plugin:{project-version}")
    }
}
apply(plugin = "org.kordamp.gradle.settings")

configure<org.kordamp.gradle.plugin.settings.ProjectsExtension> {
    directories = listOf("docs", "subprojects")
}
----

.Multi-Level

A project with the following structure

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
├── guide
│   └── guide.gradle
└── subprojects
    ├── project1
    │   ├── project1.gradle
    └── project2
        └── project2.gradle
----

Can be configured as follows

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.settings.gradle
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.kordamp.gradle:settings-gradle-plugin:{project-version}'
    }
}
apply plugin: 'org.kordamp.gradle.settings'

projects {
    layout = 'multi-level'
    directories = [
        'guide',
        'subprojects/project1',
        'subprojects/project2'
    ]
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.settings.gradle.kts
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("org.kordamp.gradle:settings-gradle-plugin:{project-version}")
    }
}
apply(plugin = "org.kordamp.gradle.settings")

configure<org.kordamp.gradle.plugin.settings.ProjectsExtension> {
    layout = "multi-level"
    directories = listOf(
        "guide",
        "subprojects/project1",
        "subprojects/project2"
    )
}
----

.Standard

A project with the following structure

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
├── guide
│   └── guide.gradle
├── project1
│   └── project1.gradle
└── project2
    └── project2.gradle
----

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.settings.gradle
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.kordamp.gradle:settings-gradle-plugin:{project-version}'
    }
}
apply plugin: 'org.kordamp.gradle.settings'

projects {
    layout = 'standard'
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.settings.gradle.kts
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("org.kordamp.gradle:settings-gradle-plugin:{project-version}")
    }
}
apply(plugin = "org.kordamp.gradle.settings")

configure<org.kordamp.gradle.plugin.settings.ProjectsExtension> {
    layout = "standard"
}
----

.Explicit

A project with the following structure

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
├── guide
│   └── guide.gradle
└── subprojects
    ├── project1
    │   ├── project1.gradle
    └── project2
        └── project2.gradle
----

Can be configured as follows

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.settings.gradle
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.kordamp.gradle:settings-gradle-plugin:{project-version}'
    }
}
apply plugin: 'org.kordamp.gradle.settings'

projects {
    layout = 'explicit'
    includeProject('guide')
    includeProjects('subprojects')
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.settings.gradle.kts
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("org.kordamp.gradle:settings-gradle-plugin:{project-version}")
    }
}
apply(plugin = "org.kordamp.gradle.settings")

configure<org.kordamp.gradle.plugin.settings.ProjectsExtension> {
    layout = "explicit"
    includeProject("guide")
    includeProjects("subprojects")
}
----

Filename transformations are applied to candidate build files, for example

.Addition

A project with the following structure

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
├── core
│   └── project-core.gradle
└── ext
    └── project-ext.gradle
----

Can be configured as follows

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.settings.gradle
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.kordamp.gradle:settings-gradle-plugin:{project-version}'
    }
}
apply plugin: 'org.kordamp.gradle.settings'

projects {
    layout = 'standard'
    fileNameTransformation = 'add'
    prefix = 'project-'
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.settings.gradle.kts
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("org.kordamp.gradle:settings-gradle-plugin:{project-version}")
    }
}
apply(plugin = "org.kordamp.gradle.settings")

configure<org.kordamp.gradle.plugin.settings.ProjectsExtension> {
    layout = "standard"
    fileNameTransformation = "add"
    prefix = "project-"
}
----

.Removal

A project with the following structure

[source,groovy]
----
.
├── build.gradle
├── settings.gradle
├── project-core
│   └── core.gradle
└── project-ext
    └── ext.gradle
----

Can be configured as follows

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.settings.gradle
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.kordamp.gradle:settings-gradle-plugin:{project-version}'
    }
}
apply plugin: 'org.kordamp.gradle.settings'

projects {
    layout = 'standard'
    fileNameTransformation = 'remove'
    prefix = 'project-'
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.settings.gradle.kts
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("org.kordamp.gradle:settings-gradle-plugin:{project-version}")
    }
}
apply(plugin = "org.kordamp.gradle.settings")

configure<org.kordamp.gradle.plugin.settings.ProjectsExtension> {
    layout = "standard"
    fileNameTransformation = "remove"
    prefix = "project-"
}
----

