
[[_org_kordamp_gradle_sonar]]
= SonarQube

[horizontal]
id:: `org.kordamp.gradle.sonar`
class:: `org.kordamp.gradle.plugin.coveralls.SonarPlugin`
(link:api/org/kordamp/gradle/plugin/sonar/SonarPlugin.html[groovydoc],
link:api-html/org/kordamp/gradle/plugin/sonar/SonarPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`, +
`link:https://plugins.gradle.org/plugin/org.sonarqube[org.sonarsource.scanner.gradle:sonarqube-gradle-plugin]`

Configures the SonarQube gradle plugin to analyze your project with link:https://www.sonarqube.org/[SonarQube]. +
If link:https://www.eclemma.org/jacoco/[JaCoCo] is enabled, the output of the
<<_task_aggregate_jacoco_report,aggregateJacocoReport>> task is used as input for the sonarqube task. +
For kotlin projects, if link:https://arturbosch.github.io/detekt/[detekt] is enabled, the output of the
<<_task_aggregate_detekt,aggregateDetekt>> task is also used as input for the sonarqube task.

[[_org_kordamp_gradle_sonar_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    quality {
        sonar {
            enabled
            hostUrl
            username
            projectKey
            ignoreFailures
            configProperties
        }
    }
}
----

.Properties
[options="header", cols="5*"]
|===
| Name             | Type                | Required | Default Value                                 | Description
| enabled          | boolean             | no       | true                                          | Disables `org.kordamp.gradle.sonar` plugin if `false`
| hostUrl          | String              | no       | 'https://sonarcloud.io'                       | The server URL to publish the sonar analysis to
| username         | String              | yes      |                                               | The login or authentication token of a SonarQube user with Execute Analysis permission on the project.
| projectKey       | String              | no       | $username + '_' + ${project.rootProject.name} | The project's unique key.
| ignoreFailures   | boolean             | no       | true                                          |
| excludedProjects | Set<Project>        | no       | []                                            | Projects in the set are excluded from aggregation
| configProperties | Map<String, Object> | no       | [:]                                           |
|===

This block should be configured on the root project.

.Mapping of Kordamp to SonarQube properties
[options="header", cols="3*"]
|===
| Plugin Property | SonarQube Property | Comment
| `config.quality.sonar.hostUrl`                  | `sonar.host.url`                       |
| `config.quality.sonar.projectKey`               | `sonar.projectKey`                     |
| `config.quality.sonar.excludes`                 | `sonar.exclusions`                     |
| `config.coverage.jacoco.aggregateReportXmlFile` | `sonar.coverage.jacoco.xmlReportPaths` | if jacoco is enabled
| 'build/reports/detekt/aggregate.xml'            | `sonar.kotlin.detekt.reportPaths`      | if detekt is enabled
|===

The SonarQube property `sonar.tests` is enriched automatically with the respective test sets,
if any of the <<_org_kordamp_gradle_integrationtest,org.kordamp.gradle.integration-test>>
or <<_org_kordamp_gradle_functionaltest,org.kordamp.gradle.functional-test>> plugins are enabled. +
Likewise, the SonarQube property `sonar.java.test.binaries`

.Methods

void exclude(String):: Adds a source exclusion rule (Ant pattern).
void excludeProject(Project):: Exclude a project from sonar analysis.

[[_org_kordamp_gradle_sonar_tasks]]
== Tasks

[[_task_sonarqube]]
=== Sonarqube

Runs the code analysis with SonarQube. +
Consumes settings from `config.quality.<<_org_kordamp_gradle_sonar_dsl,sonar>>`. +
This task is added to the root project.

[horizontal]
Name:: sonarqube
Type:: `org.sonarqube.gradle.SonarQubeTask`
