
[[_org_kordamp_gradle_source]]
= SourceJar

[horizontal]
id:: `org.kordamp.gradle.source-jar`
class:: `org.kordamp.gradle.plugin.source.SourceJarPlugin`
    (link:api/org/kordamp/gradle/plugin/source/SourceJarPlugin.html[groovydoc],
     link:api-html/org/kordamp/gradle/plugin/source/SourceJarPlugin.html[source])
applies:: `<<_org_kordamp_gradle_base,org.kordamp.gradle.base>>`

Packages the project's source code into a single JAR file.

[[_org_kordamp_gradle_source_dsl]]
== DSL

[source,groovy]
[subs="+macros"]
----
config {
    artifacts {
        source {
            enabled
            <<_source_aggregate,aggregate>> {
                enabled
                excludedProjects
            }
        }
    }
}
----

[options="header", cols="5*"]
|===
| Name    | Type    | Required | Default Value | Description
| enabled | boolean | no       | true          | Disables `org.kordamp.gradle.source-jar` plugin if `false`
|===

This block is optional.

[[_source_aggregate]]
*aggregate*

[options="header", cols="5*"]
|===
| Name             | Type         | Required | Default Value | Description
| enabled          | boolean      | no       | true          | Enables or disables aggregation
| excludedProjects | Set<Project> |          | []            | Projects in the set are excluded from aggregation
|===

This block should be configured on the root project.

[[_org_kordamp_gradle_source_tasks]]
== Tasks

[[_task_aggregate_sources_jar]]
=== AggregateSourcesJar

Collects the results of the `sourcesJar` tasks. +
This task is added to the root project.

[horizontal]
Name:: aggregateSourcesJar
Type:: `org.gradle.api.tasks.bundling.Jar`

.Properties
[horizontal]
destinationDir:: `${rootProject.buildDir}/build/libs`

[[_task_sources_jar]]
=== SourcesJar

An archive of the source code.

[horizontal]
Name:: sourcesJar
Type:: `org.gradle.api.tasks.bundling.Jar`

.Properties
[horizontal]
classifier:: sources
destinationDir:: `${project.buildDir}/build/libs`
from:: `project.sourceSets.main.allSource`
